### ISSUE TITLE
how to test if the solution is working

### ISSUE THREAD

**Issue by shen6653** [MaxToyberman/react-native-ssl-pinning#10]
I followed the guide and added the solution for iOS app. How do I test the solution to make sure it works? I tried to replace the certificate with a different one and that does not seem to make any difference.
Our server is a virtual host and I had to use "openssl s_client -showcerts -servername <server_hostname> -connect <server_hostname>:443" to get the certificate. Does the solution works for vhost?

**Comment by shen6653** [comment]
Figured out how to test the solution by setting up Burp scanner. Ran into the 'Get' request issue that was fixed recently in https://github.com/MaxToyberman/react-native-ssl-pinning/commit/98bcb0fcc303204539a1c9579f9c8fa5d5c3d69d (Thanks!)

Verified that the solution worked for REST API calls made through fetch() but not GraphQL API calls made through graphql().

**Comment by MaxToyberman** [comment]
You can also use CharlesProxy to check the solution .
see this for reference: 
`https://medium.com/@zhangqichuan/explain-ssl-pinning-with-simple-codes-eaee95b70507`
