### ISSUE TITLE
Javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: Failure in SSL library, usually a protocol error

### ISSUE THREAD

**Issue by hanifmhd** [MaxToyberman/react-native-ssl-pinning#102]
I found error when running on android version < 4.4
<img width="1344" alt="Screen Shot 2020-11-20 at 10 40 48" src="https://user-images.githubusercontent.com/15220788/99758015-3f40e780-2b23-11eb-8fe5-b928f344b738.png">

**Comment by MaxToyberman** [comment]
Android4 is not supported by okhttp3, if you want support for it i have a branch **_Android4Support_**

**Comment by MaxToyberman** [comment]
@hanifmhd  please refer to this issue: 
https://github.com/MaxToyberman/react-native-ssl-pinning/issues/79

**Comment by hanifmhd** [comment]
How do i install the lib? download the source code on branch "android4support" and put it manually on "node_modules" folder in my local?

**Comment by hanifmhd** [comment]
> @hanifmhd please refer to this issue:
> #79

i still got error after install from branch Android4Support
