### ISSUE TITLE
Support for dynamic SSL Pinning

### ISSUE THREAD

**Issue by moxspoy** [MaxToyberman/react-native-ssl-pinning#105]
Hallo everyone!

One major drawback of using embedde SSL pinning is the certificate's expiration date. The certificate expiration forces user to update application regularly before the certificate expires. Unfortunatelly, some percentage of users don't update their apps automatically. In effect, users on older versions, will not be able to contact the application servers.

In other native library, for example https://github.com/wultra/ssl-pinning-android, they have ability to make dynamic ssl pinning.

I did not get any information in readme (or this library is not support yet) about dynamic SSL Pinning. So, is this library support SSL Pinning?

Thank you!

**Comment by MaxToyberman** [comment]
Hi @moxspoy  you can you public key pinning to achieve this.
this library works with okHttp library and not ssl-pinning-android

**Comment by moxspoy** [comment]
how to use pkpinning on ios? is it possible without embedded the cert?

**Comment by MaxToyberman** [comment]
@moxspoy you need to embed it only ones.
public key will be extracted automatically

**Comment by praveennachi60** [comment]
@MaxToyberman If certificate is expired,  how can i update the public key?
