### ISSUE TITLE
The certificate for this server is invalid. You might be connecting to a server that is pretending to be “...” which could put your confidential information at risk.

### ISSUE THREAD

**Issue by in-html** [MaxToyberman/react-native-ssl-pinning#106]
I am trying to do this but get error (IOS 14.2):

**The certificate for this server is invalid. You might be connecting to a server that is pretending to be “https://...” which could put your confidential information at risk.**

I copied the .cer certificate into xcode and do this:

```
const response = await fetch(url, {
        method: 'POST',
        body: body,
        pkPinning: true,
        disableAllSecurity: false,
        // your certificates array (needed only in android) ios will pick it automatically
        sslPinning: {
          certs: ['my_cer_file_without_extension'], // your certificates name (without extension)
        },
        headers: {
          Accept: 'application/json; charset=utf-8',
          'Access-Control-Allow-Origin': '*',
          e_platform: 'mobile',
        },
      });
```

Am I doing something wrong or is it no longer working? Any ideas?

**Comment by MaxToyberman** [comment]
@in-html how did you create the certficates ?  can you show your request?

**Comment by moxspoy** [comment]
hallo! i got same problem.
i generate using your guide in readme.

`openssl s_client -showcerts -servername berandaunj.com -connect  berandaunj.com:443  </dev/null && openssl x509 -in mycert.pem -outform der -out mycert.cer` 

then drag that cert into my app.

my app.js
```
fetch(url, {
    headers,
    method: 'GET',
  })
    .then((response) => {
      console.log(response.bodyString);
    })
    .catch((err) => {
      console.debug('error ocured');
      console.debug(err);
    });
```

**Comment by in-html** [comment]
> @in-html how did you create the certficates ? can you show your request?

Thanks for your reply, unfortunately that's all I can show
we refused to attach the certificate right now

**Comment by dalugoda** [comment]
Any update on this? Getting the same issue. Working fine on android.
iOS version : 14

**Comment by tukhai** [comment]
I got the same issue, working fine on android, but iOS always got "The certificate for this server is invalid". Happens for different version of iOS

**Comment by JohnPoprocket** [comment]
Are there already updates also get the error on ios 14

**Comment by tan-dev122** [comment]
@in-html If you resolved this issue, can you share the solution? Working well on android, but not on iOS.

**Comment by mrmarktyy** [comment]
I am getting the same Network error message on iOS

**Comment by eliot-ye** [comment]
The certificate generated by using the key chain of Mac can solve this problem

**Comment by dalugoda** [comment]
in iOS, make sure that you add the certificate to the bundle resources. Go to Build Phases > Copy bundle resources > Add the certificate.

**Comment by AmaanKulshreshtha** [comment]
Getting the same error. Even tried adding the certificate in the "Copy bundle resources" phase. Can anyone provide any update on this?

**Comment by rosen777** [comment]
I am also getting the same error. I have also tried what I can think of both with public key and certificate pinning and following the XCode steps.

**Comment by NewcodeTechnology** [comment]
Did anyone fix this I have the same error it is working fine on android I have been looking everywhere for a solution.

If anyone knows anything please let me know.

Thanks

**Comment by thahseen21** [comment]
is there any solution for this in ios ?

**Comment by Moustafa-mahmaed** [comment]
any solution for this issue
 ?!!!!!!

**Comment by satyammca** [comment]
Please let us know if anyone found the solution for this issue

**Comment by suleymanbasbug** [comment]
I am having the same problem. Can anyone who has found a solution share it? I am using a self-signed certificate.

**Comment by BurleVineeth** [comment]
Still searching in 2024, Has anyone found a solution? Please tell us if anyone knows about it.

**Comment by KalpeshJetaniSS** [comment]
is anyone could find solution ?

**Comment by BurleVineeth** [comment]
Hi Bro, user charles for proxy server. That will most probably resolve your issue.
