### ISSUE TITLE
iOS requires always certificate pinning

### ISSUE THREAD

**Issue by kgsachinthaudara** [MaxToyberman/react-native-ssl-pinning#108]
Hi 

We have tried iOS for public key pinning, But it seems like library always require SSL certificate as well. So this is not good and as my knowledge we need to update certificate often and also need to do a new app release. So how do I implement iOS for only public key pining without certificate ?

Thanks

**Comment by MaxToyberman** [comment]
Hi @kgsachinthaudara 
The public key is extracted from the certificates, it doesn't mean that it uses certificate pinning.
you can see it [here](https://stackoverflow.com/questions/24615144/afnetworking-pin-public-key-for-a-trusted-certificate)
