### ISSUE TITLE
com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by bart8253** [MaxToyberman/react-native-ssl-pinning#111]
@MaxToyberman 
i'm have to use ssl pinning because our web server is protected by Firewall. (like 'Netscaler')
When use fetch from react-native-ssl-pinning to test, it cannot be accessed to our server.

and our certificate is on [projectName]/android/app/src/main/assets/cert.cer

![스크린샷 2021-02-05 오후 12 38 47](https://user-images.githubusercontent.com/78578959/106987166-353c9580-67b0-11eb-87c7-0e718a9c07d3.png)

userLoginTest(id, pw) {
    var url = new URL('https://url/logintest')

    id = encrypt(id)
    pw = encrypt(pw)

    var params = JSON.stringify({
      id: id,
      pw: pw
    })

    return new Promise((resolve, reject) =>
    fetchSSL(url, {
        method: 'POST',
        timeoutInterval: 3000, // milliseconds
        body: params,
        sslPinning: {
          certs: ['cert']
        },
        headers: {
          Accept: "application/json; charset=utf-8", "Access-Control-Allow-Origin": "*", "e_platform": "mobile",
        },
      }).then(response => {
        console.log('response', response)
        });
      }).catch(error => {
          Alert.alert(error)
          resolve(null)
      })
    );
  }

  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.13.4",
    "@react-native-community/datetimepicker": "^3.0.9",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-firebase/app": "^10.6.1",
    "@react-navigation/material-top-tabs": "^5.3.13",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-crypto-js": "^1.0.0",
    "react-native-elements": "^3.1.0",
    "react-native-exit-app": "^1.1.0",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.17.1",
    "react-native-simple-toast": "^1.1.3",
    "react-native-ssl-pinning": "^1.5.2",
    "react-native-svg": "^12.1.0",
    "react-native-svg-charts": "^5.4.0",
    "react-native-tab-view": "^2.15.2",
    "react-native-vector-icons": "^8.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }

**Comment by bart8253** [comment]
And it is working on debug mode (when connect to React Native Debugger with Chrome), 
but not on release mode.

**Comment by mohdmunaf** [comment]
@ghost How did this get solved?
