### ISSUE TITLE
Quick questions about the library

### ISSUE THREAD

**Issue by sbrighiu** [MaxToyberman/react-native-ssl-pinning#115]
If I just want to use the sha-256 base64 strings as the example, this is the whole implementation I need to add?
``` 
import { fetch } from 'react-native-ssl-pinning';

fetch("<MY_ENDPOINT_URL>", {
 	method: "<HTTP_METHOD>" ,
        timeoutInterval: <TIMEOUT_IN_MS>,
 	pkPinning: true,
 	sslPinning: {
 		certs: [
                      "sha256/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=", // production cert
                      "sha256/AAAAAAAABBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=", // dev cert
                      "sha256/AAAAAAAACCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" // backup cert
                ] 
 	}
})
```

1. I don't need to add certs in the native project, right? (Yes I read the README.md, but I want to make sure :) )
2. Are the domains automatically detected based on <MY_ENDPOINT_URL>? Does this setup also allow subdomains?
3. Just to be sure, I know how it sounds :) ... Will any other calls made from RN or native be affected by this method of ssl pinning, or just the calls made via `{ fetch } from 'react-native-ssl-pinning';`. I'm asking because I use Firebase SDKs and some media content streaming, which may not be all on our servers. My realm database is also freaking out a bit :)

**Comment by sbrighiu** [comment]
@MaxToyberman

**Comment by MaxToyberman** [comment]
@sbrighiu 

1. for android you need only hashes, for iOS you need to add certificates and hashes will be extracted from them.
2. didnt check it but you should not have any problems.
3. just calls made via fetch

**Comment by sbrighiu** [comment]
So basically i could just leave the top code and fill in my real sha256 keys, and just add certs in iOS Project resources.

**Comment by sbrighiu** [comment]
Any idea how i can test iOS part without:
1. Changing the server cert, and then trying to validate with the old one.
2. Running everything through a proxy env.

I just want to validate it is working and that it would do its job... Might have to look into AFNetworking docs.. It's been a while..
