### ISSUE TITLE
SSL Context is not initialized. 

### ISSUE THREAD

**Issue by Majdewave** [MaxToyberman/react-native-ssl-pinning#119]
hi, im facing SSL Context is not initialized error. 
this is my trusting: 
 private static X509TrustManager initSSLPinning(ReadableArray certs) {
        X509TrustManager trustManager = null;

        try {
            sslContext = SSLContext.getInstance("TLS");
            CertificateFactory cf = CertificateFactory.getInstance("X.509");
            String keyStoreType = KeyStore.getDefaultType();
            KeyStore keyStore = KeyStore.getInstance(keyStoreType); 
            char[] password = "Boj2020!".toCharArray();

            for (int i = 0; i < certs.size(); i++) {
                String filename = certs.getString(i);
                InputStream caInput = new BufferedInputStream(OkHttpUtils.class.getClassLoader().getResourceAsStream("assets/" + filename + ".cer"));
                Certificate ca;
                try {
                    //keyStore.load(caInput, password); // for pfx cert
                    keyStore.load(caInput, password);
                    ca = cf.generateCertificate(caInput);
                } finally {
                    caInput.close();
                }
                keyStore.setCertificateEntry(filename, ca);
            }
            String tmfAlgorithm = TrustManagerFactory.getDefaultAlgorithm();
            TrustManagerFactory tmf = TrustManagerFactory.getInstance(tmfAlgorithm);
            tmf.init(keyStore);

            TrustManager[] trustManagers = tmf.getTrustManagers();
            if (trustManagers.length != 1 || !(trustManagers[0] instanceof X509TrustManager)) {
                throw new IllegalStateException("Unexpected default trust managers:" + Arrays.toString(trustManagers));
            }
            trustManager = (X509TrustManager) trustManagers[0];

            sslContext.init(null, new TrustManager[]{trustManager}, null);

        } catch (Exception e) {
            e.printStackTrace();
        }
        return trustManager;
    }

my cert file is in Assets folder.
and im sending the cert name like that: 
sslPinning: {
        certs: ["acptamancli"]
}

 i can get it,  and generate the certificate :  ca = cf.generateCertificate(caInput), after this i'm recieving : SSL Context is not initialized. 

who can help please ?

**Comment by MaxToyberman** [comment]
@Majdewave did you run react-native run-android after adding certificate ?
