### ISSUE TITLE
Support for Self-Signed Cert?

### ISSUE THREAD

**Issue by kelokchan** [MaxToyberman/react-native-ssl-pinning#12]
Will there be support for api endpoint which is self-signed?

**Comment by filiptdz** [comment]
I've never tried it, so I don't know if there are any caveats, but in theory it should already be supported. The only issue is adding the certificates to the device, but you can find plenty of tutorials online for that.

**Comment by MaxToyberman** [comment]
@kelokchan it should be supported already

**Comment by MaxToyberman** [comment]
@kelokchan  do you experience any problems ?

**Comment by kelokchan** [comment]
> @kelokchan do you experience any problems ?

Not anymore. My issue was related to webview which I suppose have nothing to do with this library.

**Comment by SrBrahma** [comment]
> > @kelokchan do you experience any problems ?
> 
> Not anymore. My issue was related to webview which I suppose have nothing to do with this library.

@kelokchan Did you need SSL for webview? I am on the same boat right now, so I can tokenize the user's credit card.
