### ISSUE TITLE
Certificate is expiring

### ISSUE THREAD

**Issue by Maharshi01** [MaxToyberman/react-native-ssl-pinning#121]
Hi @MaxToyberman,

Iam using Public Key Pinning (using hash for android and uploaded the .cer file in the iOS root folder) in my react-native application. My certificate is going to expire in april, so i want to know whether if i can still use the app even after certificate is expired or do i have to renew the certificate and replace that in the iOS folder and release the app? will the public key be same even after certificate is renewed?

**Comment by MaxToyberman** [comment]
Hi @Maharshi01 ,
public key should be the same, you don't need to replace the certificate in iOS folder.

**Comment by Maharshi01** [comment]
ok, thanks @MaxToyberman

**Comment by kgsachinthaudara** [comment]
@MaxToyberman you mean no need to worry about certificate expire of existing live app ?
