### ISSUE TITLE
Where to put this code?

### ISSUE THREAD

**Issue by tanz98** [MaxToyberman/react-native-ssl-pinning#122]
hello i first time to using this library for security, i am not understand where i put this code to implement ssl pinning. is ssl pinning use when i fetch data like post, delete, update api? or just in one file to protect this apps attack?

**Comment by ududsha** [comment]
Hi @tanz98, this is mostly going with Mobile apps. You can read more here. [https://www.raywenderlich.com/1484288-preventing-man-in-the-middle-attacks-in-ios-with-ssl-pinning](https://www.raywenderlich.com/1484288-preventing-man-in-the-middle-attacks-in-ios-with-ssl-pinning ). This npm library helps you to implement it using **fetch**. Hope this will help you!

**Comment by tanz98** [comment]
@ududsha ok thank you i already half understand, just confirmation: so i must put fetch in every request data our api?
