### ISSUE TITLE
Is there a way to use this with GraphQL requests?

### ISSUE THREAD

**Issue by spsaucier-bakkt** [MaxToyberman/react-native-ssl-pinning#123]
We're using `@apollo/client` for most requests from the back-end, so we aren't able to use the `fetch` methods in the documentation. Is there a way to enable SSL pinning requirements on GraphQL requests?

**Comment by MaxToyberman** [comment]
Hi @spsaucier-bakkt i am not familiar with GraphQL, i don't think this library can be used with it.

**Comment by dacevedo12** [comment]
It can be used, just specify the fetch option on your http link

**Comment by mrmarktyy** [comment]
> It can be used, just specify the fetch option on your http link

Thank you @dacevedo12 for the reply.
Would you mind add a snippet code around add fetch option with http link 

Thanks!

**Comment by dacevedo12** [comment]
Sure

```javascript
import { fetch as sslPinningFetch } from "react-native-ssl-pinning";

const secureFetch = async (uri, options) =>
  sslPinningFetch(uri, {
    ...options,
    pkPinning: true,
    sslPinning: {
      certs: ["sha256/your_cert_goes_here"],
    },
  });

const httpLink = createHttpLink({
  fetch: secureFetch,
  uri: `https://www.something.com/api`,
});
```

You can learn more about using a custom fetch at the official docs https://www.apollographql.com/docs/react/api/link/apollo-link-http/#customizing-fetch

**Comment by jigneshpatel-dreampay** [comment]
It is giving me an error for fetch: secureFetch type mismatch.
Type '(uri: string, options: ReactNativeSSLPinning.Options) => Promise<ReactNativeSSLPinning.Response>' is not assignable to type '(input: RequestInfo, init?: RequestInit | undefined) => Promise<Response>'.

**Comment by dacevedo12** [comment]
@jigneshpatel-dreampay It's been almost a year, so it's very likely the type definitions have changed :sweat_smile: 

I'm no longer working on react native apps, but it can probably be adapted based on the snippet. It's a matter of creating a way for apollo's fetch to interact with ssl-pinning's fetch function

**Comment by SarviroRoman** [comment]
> [dacevedo12](https://github.com/dacevedo12)
> 
> It is giving me an error for fetch: secureFetch type mismatch.
> 
> `Type '(uri: string, options: ReactNativeSSLPinning.Options) => Promise<ReactNativeSSLPinning.Response>' is not assignable to type '(input: RequestInfo, init?: RequestInit | undefined) => Promise<Response>'.`

Hello, do you have a working example?
I'll be very thankful)
