### ISSUE TITLE
Can not display network traffic when use Sentry or Chucker

### ISSUE THREAD

**Issue by moxspoy** [MaxToyberman/react-native-ssl-pinning#124]
# What the problem

I use [Sentry](https://sentry.io/) as monitoring tools for the application (it records error and network traffic).
We also use [chucker library](https://github.com/ChuckerTeam), to monitor network traffic in the app.

After i use react-native-ssl-pinning library, i notice that the API request can not be logged (we can not see displayed network traffic data both in chucker and sentry).

We compare before and after use this library, and we figured out that the network traffic successfully logged when we dont use react-native-ssl-pinning library

# actual
![image](https://user-images.githubusercontent.com/17137806/112110545-a19b1900-8be5-11eb-911f-4030c320d43b.png)

# expected
![image](https://user-images.githubusercontent.com/17137806/112110597-b7a8d980-8be5-11eb-9d21-0f965a6e0d2b.png)

what im expected  i'm still can use logging tools such as sentry or chucker to see network traffic.

Can you help me ? Is it interceptor problem or somehting like that? 

# Version
- React Native 0.61.5
- Sentry 2.3.0
- SSL Pinning 1.5.2

**Comment by MaxToyberman** [comment]
hi @moxspoy 
try to add `disableAllSecurity` to request, to monitor it

**Comment by moxspoy** [comment]
disableAllSecurity will make apps not use SSL Pinning right?

i mean, i want to keep SSL Pinning security, except for some third party library like Sentry (in production).

Any ideas?

**Comment by abdullahizzuddiin** [comment]
Hi, 

It seems I got the same problem. Any updates for this issue?

**Comment by MaxToyberman** [comment]
Hi,
disableAllSecurity will make apps not use SSL Pinning.

It is not an issue, one of the reasons to use ssl pinning is to avoid monitoring
