### ISSUE TITLE
How to check our apps already using ssl pinning

### ISSUE THREAD

**Issue by anuk112** [MaxToyberman/react-native-ssl-pinning#126]
hello i was try to protect apps from ssl pinning attack, my friends recommended using this library for react native apps. But i still don't understand how to check our apps already protect from ssl pinning attack with this library. 

I already implement with Certificate Pinning method : 

```
import {fetch} from 'react-native-ssl-pinning';

fetch(url, {
	method: "POST" ,
	timeoutInterval: communication_timeout, // milliseconds
	body: mybody,
	// your certificates array (needed only in android) ios will pick it automatically
	sslPinning: {
		certs: ["wrong-cert",""] // i was use wrong-cert to test is my ssl already running or not
	},
	headers: {
		Accept: "application/json; charset=utf-8", "Access-Control-Allow-Origin": "*", "e_platform": "mobile",
	}
})
.then(response => {
	console.log(`response received ${response}`)
})
.catch(err => {
	console.log(`error: ${err}`)
})
```

in above sample i try use wrong-cert to test my ssl cert already running or not,but i still can connect to server. How to fix that?

**Comment by sendyputra** [comment]
you can try use HttpCanary App to capture network and if you want try MiTM use Parallel App
