### ISSUE TITLE
iOS Public Key Pinning

### ISSUE THREAD

**Issue by omer921** [MaxToyberman/react-native-ssl-pinning#136]
I want to clarify: 
When setting up Public Key Pinning in iOS you mention `your certificates array (needed only in android) ios will pick it automatically`

Where is iOS picking up the public key? What are the implications if the certificate changes on the server side? Should I still include my list of certificates as follows 

`fetch(url, {
    pkPinning: true,
    sslPinning: {
      certs: ['cert']
    },
  })`

**Comment by carlosen14** [comment]
same here. I've put the .cer file on these locatios where I guess it can be taken, but still doesn't work on iOS.

![image](https://user-images.githubusercontent.com/9368632/143931446-b9fd28b8-f2e8-4311-901e-1eed0f0317d8.png)

**Comment by deepakverma4** [comment]
@omer921  did you manage to get it working in iOS?

**Comment by omer921** [comment]
@deepakverma4 Yes, I just needed to add the certificates to the "Copy Bundle Resources" step.

**Comment by eugustavo** [comment]
> @deepakverma4 Yes, I just needed to add the certificates to the "Copy Bundle Resources" step.

I'm having problems with this question, could you help me?

**Comment by sdevansh96** [comment]
Certificate pinning is working for iOS.
Public key pinning is not working

**Comment by ndpiparava** [comment]
@sdevansh96  is there any officla doc why Public key pinning is not working does not work for iOS

**Comment by mohdmunaf** [comment]
Have you found any solve? @ndpiparava
