### ISSUE TITLE
support for nontext responses

### ISSUE THREAD

**Issue by kkmate** [MaxToyberman/react-native-ssl-pinning#137]
Hi @MaxToyberman,

we ultimately need support for non-text responses, in particular we stuck at processing binary pdf data. Would you consider taking new pr if we come up with a feasible solution for that? Just asking because if you have no capacity for this, we wouldn't even start the process.

Thanks!

**Comment by martinfejes** [comment]
Hi @MaxToyberman 

I created a Pull-request for this use-case. https://github.com/MaxToyberman/react-native-ssl-pinning/pull/138

Let us know if you consider merging it into your library or not.

Thanks

**Comment by MaxToyberman** [comment]
Thanks @martinfejes will publish a version by end of the week
