### ISSUE TITLE
Error: SSLContext is not initialized

### ISSUE THREAD

**Issue by Sworzen1** [MaxToyberman/react-native-ssl-pinning#149]
Hello, I try fetch but I get error: SSLContext is not initialised. Its Android emulator.
I have cert in assests with .cer extension and my request shows like : 
` fetch(url, {
  method: 'GET',
	timeoutInterval: 1000,
	sslPinning: {
		certs: ["mycert"] 
	},
  headers: {
    Accept: "application/json; charset=utf-8",
}
})
.then(response => {
	console.log(response)
})
.catch(err => {
  console.log(err)
})`

**Comment by Xatybes** [comment]
hi, I got the same issue, how did you solve it?

**Comment by wiscaksono** [comment]
how do you resolve this ?

**Comment by wiscaksono** [comment]
@HareHanum no
