### ISSUE TITLE
NPM >= v7 throws "npm ERR! peer react-native@"^0.41.2" from react-native-ssl-pinning@1.5.4"

### ISSUE THREAD

**Issue by mppperez** [MaxToyberman/react-native-ssl-pinning#153]
`npm install` will fail because of the peer dependency to React Native in package.json:

https://github.com/MaxToyberman/react-native-ssl-pinning/blob/8fc08635e7240fbfa909ed59b3a2bcf4120690d3/package.json#L20

Error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: sample@1.0.0
npm ERR! Found: react-native@0.67.3
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.41.2" from react-native-ssl-pinning@1.5.4
...
```

I've seen other projects deleting the peer dependency completely or changing it to any version (*). Is it possible to adapt such a change and release the library to make it compatible to newer versions of NPM (without using `--legacy-peer-deps`)?

**Comment by alemarra89** [comment]
Same problem here

**Comment by MaxToyberman** [comment]
merge Thank you @alemarra89

**Comment by alemarra89** [comment]
> merged Thank you @alemarra89

I think you should update package version and then re-publish new version in the npm registry.
