### ISSUE TITLE
Support for public key pinning?

### ISSUE THREAD

**Issue by ehf5307** [MaxToyberman/react-native-ssl-pinning#16]
Any plans to support public key pinning in addition to cert pinning? 

Thanks

**Comment by MaxToyberman** [comment]
@ehf5307 i will add this option soon, a pr is also welcomed.

**Comment by yuppieghost** [comment]
how's that going? Hope to see that support

**Comment by yuppieghost** [comment]
> @ehf5307 i will add this option soon, a pr is also welcomed.

how's that going? Hope to see that support

**Comment by MaxToyberman** [comment]
@yuppieghost @ehf5307  I have added public key pinning in version 1.4.0
