### ISSUE TITLE
Autolinking broken after React Native update 0.69.0

### ISSUE THREAD

**Issue by mansdahlstrom1** [MaxToyberman/react-native-ssl-pinning#160]
Since React Native version 0.69 this package does not auto-link correctly anymore. As stated here: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#platform-ios the `.podspec` file must be in the root folder of the project, before it was possible to have

**Docs after 0.69:** 
This means that all libraries need to ship a Podspec in the root of their folder. Podspec references the native code that your library depends on.

**Docs before 0.69:**
This means that all libraries need to ship a Podspec either in the root of their folder or where the Xcode project is. Podspec references the native code that your library depends on.

I will submit a PR to fix this issue. The change should be backwards compatible.

**Comment by farell-flip** [comment]
Will this be merged soon? This blocks my progress on my app too

**Comment by mansdahlstrom1** [comment]
Thank you for merging my PR @MaxToyberman. I created another PR with a version bump so this fix can be deployed to NPM. https://github.com/MaxToyberman/react-native-ssl-pinning/pull/164

**Comment by MaxToyberman** [comment]
Thanks @mansdahlstrom1  version 1.5.7 is available on npm
