### ISSUE TITLE
Error when doing fetch call

### ISSUE THREAD

**Issue by hotdev405** [MaxToyberman/react-native-ssl-pinning#18]
![Screenshot_1563021179](https://user-images.githubusercontent.com/50766870/61171695-90c68300-a57b-11e9-9b04-ba5dda92324b.png)

**Comment by MaxToyberman** [comment]
@hotdev405  please show me the request if you can

**Comment by MaxToyberman** [comment]
@hotdev405 do you have            
```
sslPinning: {
		certs: ["cert1","cert2"]
}
```
in your request ?

**Comment by hotdev405** [comment]
i dont get the error anymore now, but i am still able to intercept the calls made by the app using http canary and i can see the response data, so does that mean i have not configured properly ?

**Comment by MaxToyberman** [comment]
@hotdev405 yes, something is wrong

**Comment by MaxToyberman** [comment]
@hotdev405  did you find the problem ?
