### ISSUE TITLE
RNSslPinning undefined using RN 0.60.3

### ISSUE THREAD

**Issue by draperj** [MaxToyberman/react-native-ssl-pinning#19]
Hello,

Using RN 0.60.3, I am seeing the below error:

`TypeError: Cannot read property 'fetch' of undefined`
Contained within index.js:8:17

Examining the index.js for this library and troubleshooting, it appears the object RNSslPinning is null:
`import { NativeModules } from 'react-native';
import Q from 'q'

const { **RNSslPinning** } = NativeModules;
`

Linking of libraries is now handled by default in RN 0.60.+, could this be related to that?

**Comment by MaxToyberman** [comment]
@draperj which version are you using ?

**Comment by draperj** [comment]
> @draperj which version are you using ?

1.2.4

**Comment by MaxToyberman** [comment]
@draperj i have just created a new project with RN0.60.3 and it works fine.
Did you run pod install ?

**Comment by MaxToyberman** [comment]
@draperj version v1.3.0 released check it out and reopen if needed

**Comment by strfn** [comment]
@draperj have you found the solution having the same here ...

**Comment by brian7346** [comment]
Have the same problem here

**Comment by oviniciusfeitosa** [comment]
Same problem 2023...
