### ISSUE TITLE
Not Compatible with RN 0.72

### ISSUE THREAD

**Issue by pipo151086** [MaxToyberman/react-native-ssl-pinning#190]
trying tu run app with RN 0.72

after upgrading and running react-native run-android i get the following error:

Could not create task ':react-native-ssl-pinning:compileDebugJavaWithJavac'.
   > In order to compile Java 9+ source, please set compileSdkVersion to 30 or above

BUILD FAILED in 54s
error Failed to install the app. Command failed with exit code 1: gradlew.bat tasks FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':tasks'. > Could not create task ':react-native-ssl-pinning:compileDebugJavaWithJavac'. > In order to compile Java 9+ source, please set compileSdkVersion to 30 or above * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 54s

**Comment by Moayad-92** [comment]
Here is the diff that solved our problem using **patch-package**:

```diff
diff --git a/node_modules/react-native-ssl-pinning/android/build.gradle b/node_modules/react-native-ssl-pinning/android/build.gradle
index efb23b8..eae7828 100644
--- a/node_modules/react-native-ssl-pinning/android/build.gradle
+++ b/node_modules/react-native-ssl-pinning/android/build.gradle
@@ -12,7 +12,7 @@ buildscript {
 apply plugin: 'com.android.library'
 
 android {
-    compileSdkVersion 28
+    compileSdkVersion 30
     buildToolsVersion "28.0.3"
 
     defaultConfig {
```

**Comment by dogra-deepak-tftus** [comment]
add this in build file->
subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}

**Comment by HareHanum** [comment]
Did you guys manage to solve this? i tried upgrade the compileSdkVersion to 30 but still face the issue.
Can someone help?

**Comment by pipo151086** [comment]
> Did you guys manage to solve this? i tried upgrade the compileSdkVersion to 30 but still face the issue. Can someone help?

I've made a fork >


https://github.com/MaxToyberman/react-native-ssl-pinning/compare/master...pipo151086:react-native-ssl-pinning:master


"TEMOPORARY WORKAROUD"

**Comment by dogra-deepak-tftus** [comment]
You have to save .cer file in your assets to make it work.

**Comment by HareHanum** [comment]
Ive done that, but still get the same error.
on develop the app works fine, the difference between develop to my branch is the whole v0.72 upgrade changes.
develop uses version v0.67.5

**Comment by ElangoPrince** [comment]
@HareHanum  Did you solve this crash issue?

**Comment by HareHanum** [comment]
@ElangoPrince yea but it was strange, the solution was to clear data on the android device.

**Comment by rohitninawe** [comment]
Changes related to compileSdkVersion (#195 ) has been merged into a master branch.

There will be a new release in a few days 🎉
