### ISSUE TITLE
iOS GET request - Error: Cancelled

### ISSUE THREAD

**Issue by pZdravkov** [MaxToyberman/react-native-ssl-pinning#20]
Hi,

I am trying to make a secure GET request to Google Maps API but I keep getting very ambiguous error - error: cancelled.

My configuration is as follows:
```
fetch(URL, {
            method: 'GET',
            timeoutInterval: 10000,
            sslPinning: {
                certs: ['cert_google']
            }
        }
```
I have generated a certificate following the recommended steps and linked it to the XCode project.

Any ideas what is going wrong?

Thanks in advance.

**Comment by MaxToyberman** [comment]
version 1.3.1 released , please try now

**Comment by pZdravkov** [comment]
Updated to 1.3.1 in the morning it was working. Also, another thing I noticed is when I provide wrong certificates, fetching still succeeds?

Any way to check if the SSL pinning is actually working?

Cheers.

**Comment by MaxToyberman** [comment]
what certificates do you use ? you can open Charles Proxy to see that ssl pinning is working.

**Comment by pZdravkov** [comment]
Let me explain a bit so you can get a better understanding.

I've made an app that uses https.maps.googleapis.com for fetching place details and a private server for fetching some other data. What I am trying to do is secure the HTTP calls by SSL pinning but I am a total novice in this and I have no idea how it works.

Currently, I have 4 SSL certificates - 2 for Google and 2 for the other server and I have been trying to understand how the whole SSL pinning works. Also, I have noticed that the Google cert has a really short expiration date so I have been wondering what to do after it expires.

Hope this clarifies what I am trying to achieve.
