### ISSUE TITLE
AAPT: error: resource android:attr/lStar not found.

### ISSUE THREAD

**Issue by DoHue97** [MaxToyberman/react-native-ssl-pinning#207]
i'm trying to build ./gradlew assembleRelease, but i saw the error: react-native-ssl-pinning/android/build/intermediates/merged_res/release/values/values.xml:2718: AAPT: error: resource android:attr/lStar not found
"react-native-ssl-pinning": "^1.5.8",
"react-native": "0.71.18",
Anyone help me to this issue? 
![image](https://github.com/user-attachments/assets/64cf49fb-f602-4c46-aad3-090150d2f004)

**Comment by dawoodibrar** [comment]
How can you resolve this issue? I am stuck on this issue.

**Comment by erie-e9** [comment]
Facing this one too in "react-native-ssl-pinning": "^1.5.8",

**Comment by alxpub** [comment]
Changing compileSdkVersion from 30 to 31 in this file, fixes this issue for me
![image](https://github.com/user-attachments/assets/4b25e040-737e-4c9a-a1c1-08fc738cbc36)

Found this explanation
> android:attr/lStar is an attribute that was introduced in newer versions of the Android framework (Android 12, API level 31 and above). It’s part of the advanced color theming and Material You design system, related to the calculation and representation of colors in the CIELAB color space. The lStar attribute essentially represents the lightness component (the ‘L*’ in the Lab* color model) and is used by the Android system and support libraries to manage dynamic, context-aware themes and color calculations.
> 
> If your project or its dependencies use attributes that rely on newer Android theme attributes like lStar, you need to compile against a newer compileSdkVersion (at least 31) to ensure these attributes are recognized by the Android build system. If your project’s compileSdkVersion is set below 31, you’ll encounter errors because older SDK versions don’t know about the lStar attribute.

**Comment by QuatBaThien** [comment]
i have the same issue, but i tried many solution but not working. 
buildToolsVersion = "34.0.0"
compileSdkVersion = 34
targetSdkVersion = 34

buildscript {
    ext {
                buildToolsVersion = "34.0.0"
                minSdkVersion = 21
                compileSdkVersion = 34
                targetSdkVersion = 34
                ndkVersion = "26.2.11394342"
                kotlinVersion = "1.8.0"
    }
    repositories {
        google()
         mavenCentral()
    }
    dependencies {
                    classpath("com.android.tools.build:gradle")
                     classpath("com.facebook.react:react-native-gradle-plugin")
                    classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
                    classpath 'com.google.gms:google-services:4.3.13'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        mavenCentral()
    }

    configurations.all {
        resolutionStrategy {
            force 'androidx.core:core-ktx:1.12.0'
        }
    }
}

**Comment by Shiba-Kar** [comment]
```cmd

* What went wrong:
Execution failed for task ':react-native-ssl-pinning:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: /Users/shibaprasadkar/Desktop/Programming/OFFICE/REACT-NATIVE/A2ZStoreAdmin/node_modules/react-native-ssl-pinning/android/build/intermediates/merged_res/release/mergeReleaseResources/values/values.xml:2729: AAPT: error: resource android:attr/lStar not found.
```

**Comment by vishalksymentix** [comment]
subprojects {
        afterEvaluate { project ->
            if (project.hasProperty('android')) {
                project.android { compileSdkVersion 34 }
            }
        }
}

add this android/build.gradle in the bottom

**Comment by Vaibhavshyoran** [comment]
android {
    compileSdkVersion 34
    buildToolsVersion "34.0.0"
 
     defaultConfig {
        minSdkVersion 27
        targetSdkVersion 34
         versionCode 1
         versionName "1.0"
     }

Update this android/build.gradle, if your project targeting sdk is 34
