### ISSUE TITLE
timeoutInterval:100000 is not working in fetch. Timeout after 15 seconds

### ISSUE THREAD

**Issue by kapil-kumawat** [MaxToyberman/react-native-ssl-pinning#21]
timeoutInterval is not working in fetch.
automatically timeout after 15 seconds.

My Code :
 fetch(apiUrl,
      {
        method: "POST",
        sslPinning: {
          certs: ["mycert"]
        },
        timeoutInterval: 100000,
        headers: {
          "Content-Type": "application/json"
        },
        body: body
      }
    )
      .then(response => response.json())
      .then(response => {
      }).catch(error => {
        alert(error);
      })
      .done();

**Comment by kapil-kumawat** [comment]
please help

**Comment by MaxToyberman** [comment]
@kapil-kumawat  android or iOS ?

**Comment by kapil-kumawat** [comment]
Android

**Comment by kapil-kumawat** [comment]
any solution?

**Comment by MaxToyberman** [comment]
working on it @kapil-kumawat

**Comment by MaxToyberman** [comment]
@kapil-kumawat  version 1.3.0 released please check it

**Comment by MaxToyberman** [comment]
1.3.1

**Comment by kapil-kumawat** [comment]
thanks for reply.

**Comment by kapil-kumawat** [comment]
@MaxToyberman 
 I have update plugin to 1.3.1 version.
But same issue come timeout after 10-15 sec

**Comment by kapil-kumawat** [comment]
no issue in ios version
