### ISSUE TITLE
Linking - Uncomplete on Android RN 0.59.8

### ISSUE THREAD

**Issue by pZdravkov** [MaxToyberman/react-native-ssl-pinning#22]
When using react-native link the project cannot sync successfully because a maven dependency is missing from project level gradle:

Dependency needed by com.github.franmontiel:PersistentCookieJar:v1.0.1

`
    repositories {
        maven { url "https://jitpack.io" }
    }
`

Needs fixing.

**Comment by MaxToyberman** [comment]
@pZdravkov updated the readme. and a new version 1.3.0 was released today

**Comment by MaxToyberman** [comment]
1.3.1
