### ISSUE TITLE
IOS Error: cancelled while post api call

### ISSUE THREAD

**Issue by kapil-kumawat** [MaxToyberman/react-native-ssl-pinning#23]
**In IOS platform getting Cancelled error while calling post api :**

My Code :
fetch(apiUrl,
{
method: "POST",
sslPinning: {
certs: ["mycert"]
},
timeoutInterval: 100000,
headers: {
"Content-Type": "application/json"
},
body: body
}
)
.then(response => response.json())
.then(response => {
}).catch(error => {
// getting error : Cancelled here
})
.done();

**Comment by MaxToyberman** [comment]
version 1.3.1 released , please try now

**Comment by MaxToyberman** [comment]
@kapil-kumawat  this is a certificate issue

**Comment by Miti063** [comment]
I am still facing the issue of both GET & POST methods. 
It returns "Error: Cancelled". 
FYI: Certificates added to the Xcode project & using the latest version.

**Comment by MaxToyberman** [comment]
@Miti063 "Error: Cancelled" means something is not good with the certificates.

**Comment by Miti063** [comment]
@MaxToyberman Thanks for the response. But it's working on Android with the same certificate.

**Comment by sylv1b** [comment]
I'm facing the exact same problem. Works. fine on android, but fails on iOS. I use public key pinning.

**Comment by annkiitagrawaal-gep** [comment]
Hi facing the same issue... 
"react-native-ssl-pinning": "^1.4.0"
react-native: 0.60.0
react-native-cli: 2.0.1

**Comment by strawberry-code** [comment]
Same here

**Comment by annkiitagrawaal-gep** [comment]
Hi @MaxToyberman ,

Any updates on this? Please help

**Comment by MaxToyberman** [comment]
Hi ! How did you generate the certificates ?

**Comment by faisalansari20** [comment]
Hi, 

I am using public key pinning. And it is working fine on android and on IOS it return error as cancelled. Any idea what could be the issue ?

**Comment by MaxToyberman** [comment]
@faisalansari20  How did you generate the certificates  ?

**Comment by faisalansari20** [comment]
@MaxToyberman  thanks for quick response. Actually it is at server end. I am working on mobile app. I have gone through the usage part and over there was a command as below.

> openssl s_client -servername google.com -connect google.com:443 | openssl x509 -pubkey -noout | openssl rsa -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64

i replaced google.com with my domain name. And got public key printed on terminal. I used it as for public key pinning and it worked on android.

**Comment by MaxToyberman** [comment]
@faisalansari20  please follow this to generate server certificate for ios : 
https://github.com/MaxToyberman/react-native-ssl-pinning#create-the-certificates

**Comment by faisalansari20** [comment]
thanks, I am looking into it. One question on first line as 

> openssl s_client -showcerts -servername google.com -connect google.com:443 </dev/null

do i need to replace my domain with google.com ? If not then which certificate it will generate and will it be secure or it will be different than Android one because i have used there my domain name in command to get public key pinning. Sorry but i am confused.

**Comment by MaxToyberman** [comment]
@faisalansari20  hi, replace with your domain. when the certficate is created, iOS will extract the public key.

**Comment by faisalansari20** [comment]
Thanks alot @MaxToyberman, It worked

**Comment by annkiitagrawaal-gep** [comment]
> Hi ! How did you generate the certificates ?

@MaxToyberman I used https://www.ssllabs.com/ssltest/analyze.html to get the sha256 key and used public key pinning for my domain. The same works on Android but fails on iOS. Am I doing something wrong here?

**Comment by MaxToyberman** [comment]
@annkiitagrawaal-gep  yes, please follow this : 
https://github.com/MaxToyberman/react-native-ssl-pinning#create-the-certificates

**Comment by isaacmunoz440** [comment]
@MaxToyberman 
`openssl s_client -showcerts -servername [target.com] -connect [target.com]:50063 </dev/null`

This outputs 
```
    ...
    Start Time: 1596772133
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
```

Please let me know why this happens.
