### ISSUE TITLE
Able to support native side?

### ISSUE THREAD

**Issue by thetminko** [MaxToyberman/react-native-ssl-pinning#28]
Hi, I have a react native project which has API calls in React Native side and as well in native side (Java and Swift). Is it possible to support the native side?

**Comment by MaxToyberman** [comment]
@thetminko i didn't understand your question, could you elaborate please ?

**Comment by thetminko** [comment]
@MaxToyberman Thanks for the reply. 
In my situation, I have a React Native project and I am using this lib to do cert pinning for all the API calls in React Native side.
I also have background location tracking which are written in native side (Android Java and iOS Swift) and these locations are pushed to my back-end server (Android Volley and iOS URLSession). I want this API to be cert-pinned as well. Is it possible?
