### ISSUE TITLE
Unable to compile iOS / RN 0.59

### ISSUE THREAD

**Issue by moxorama** [MaxToyberman/react-native-ssl-pinning#30]
RNSslPinning.m
```
/node_modules/react-native/React/Base/RCTBridgeModule.h:10:9: 'React/RCTDefines.h' file not found
```

**Comment by MaxToyberman** [comment]
@moxorama what version of react-native-ssl-pinning are you using ?

**Comment by MaxToyberman** [comment]
@moxorama I've just created a clean project with 0.59 and latest eact-native-ssl-pinning, it works.

**Comment by moxorama** [comment]
Hi, I'm using 1.3.5,  RN 0.59.

Very strange. 
I'm able to compile it without react-native link, by manual setting react-native-ssl-pinning pod in node_modules, but I'm getting runtime error about undefined fetch in code.

**Comment by MaxToyberman** [comment]
@moxorama did you find a solution ?
