### ISSUE TITLE
SSL Context is not initialized

### ISSUE THREAD

**Issue by auliakbarh** [MaxToyberman/react-native-ssl-pinning#31]
![WhatsApp Image 2019-10-29 at 15 08 33](https://user-images.githubusercontent.com/5032631/67749038-e0638880-fa5e-11e9-8bec-1d857911f873.jpeg)

I got this error and i can't solve this.
I'm using react-native-cli: 2.0.1, react-native: 0.59.9

**Comment by dracostheblack** [comment]
what's your certs array look like, i saw this when i had .cer in mine, should just be the name of the cert with no extension

**Comment by auliakbarh** [comment]
> what's your certs array look like, i saw this when i had .cer in mine, should just be the name of the cert with no extension

this is my certs array, i had no extension in my array
sslPinning: {certs: ["borneo-indobara","borneoindobaracert"]},

**Comment by MaxToyberman** [comment]
@auliakbarh  can you show me your request ?

**Comment by MaxToyberman** [comment]
@auliakbarh did you put your certificates in assets folder ?

**Comment by nikitaKoniukh** [comment]
Hello @MaxToyberman 
I have the same issue. 
I'm sending to you my code request and some screenshots. Can you navigate me where I do a mistake?
This is on Android. In that time at iOS I got an error:  Code=-999 "cancelled" 


`async getPostFromApi() {
        await fetch(url, {
            method: "POST",
            bodyString: body,
            timeoutInterval: 10000,
            sslPinning: {
                certs: ["wdp-LeadBeClick-test"]
            },
            headers: {
                Accept: "application/json; charset=utf-8",
            }
        }).then(response => {
            if (response == null) {
                console.log(`NUL`)
            } else {
                console.log(`response received ${response}`)
            }

        }).catch(err => {
            if (err == null) {
                console.log(`NUL`)
            } else {
                console.log(`NIKITA: ${err}`)
            }

        })
    }`

<img width="283" alt="Screen Shot 2020-07-14 at 13 17 51" src="https://user-images.githubusercontent.com/44729824/87414466-85fe5e00-c5d4-11ea-84f9-438f10a8a7b3.png">

**Comment by MaxToyberman** [comment]
Hi @nikitaKoniukh  `bodyString: body` should be `body: bodyString`

**Comment by nikitaKoniukh** [comment]
@MaxToyberman thank you so much for quick response.
Yes you are right. I've changed accidentally. 
But still doesn't work...￼

**Comment by MaxToyberman** [comment]
@nikitaKoniukh what error do you get ?

**Comment by nikitaKoniukh** [comment]
On Android **SSLContext is not initialized.** 
And on iOS load failed with error **Error Domain=NSURLErrorDomain Code=-999 "cancelled"**

**Comment by MaxToyberman** [comment]
Did you run react-native run-android after you added the cert ?

**Comment by nikitaKoniukh** [comment]
Yes of course, usually I run: **npx react-native run-android**

**Comment by nikitaKoniukh** [comment]
I'm using RN 0.60+ and for installation I've use command 
**$ npm install react-native-ssl-pinning --save** and **pod install** for iOS

**Comment by MaxToyberman** [comment]
@nikitaKoniukh can you mail me the full request so i can debug it ?

**Comment by nikitaKoniukh** [comment]
I'm sorry but it's impossible￼. Because this certificate it is from production backend. 
I spoke with backend developers and they gave me certificate key and password. Where I can put them in my project. At postman I know how to add certificate with a key and password. ￼￼￼￼￼￼

**Comment by MaxToyberman** [comment]
@nikitaKoniukh and how do you put it in postman ? didn't see an option like that

**Comment by nikitaKoniukh** [comment]
@MaxToyberman Can't find a solution how I can do SSL pinning with this .key file. 
Please check the screenshot how I can add this key to postman:
![Screen Shot 2020-07-15 at 9 08 20](https://user-images.githubusercontent.com/44729824/87509792-fa8bd800-c67a-11ea-8350-f5be299f134c.png)

**Comment by amitpadmani-awts** [comment]
Facing the same issue @nikitaKoniukh have you find any solution? Will help me a lot

**Comment by nikitaKoniukh** [comment]
@amitpadmani-awts hey. My problem was that I'm using certificate with private key. We discussed with backend and figured out that it's not secure. I'm waiting for the public keys from them. Next week I'll implement it.

**Comment by amitpadmani-awts** [comment]
> @amitpadmani-awts hey. My problem was that I'm using certificate with private key. We discussed with backend and figured out that it's not secure. I'm waiting for the public keys from them. Next week I'll implement it.

Okay @nikitaKoniukh, I also resolved the issue. I was added .crt file instance of .cer.

**Comment by layeng** [comment]
Hi
I am doing this software today, adding ssl pinning and I also have the error SSLContext is not initialised. For those who have found the solution, please advise me. I am using a url which is www.gimperservices.com . The commodo cert that we use is www.gimperservices.com.crt which we convert to www.gimperservices.com.cer .  I have put all the www.gimperservices.com certs (crt and cer) at android\app\src\main\assets . The code is as follows:

 submit = async () => {

      let objects = {
          "user":this.state.user,
          "password":this.state.password,
          "MAC":this.state.mac
       }

   // console.log("objects",objects)
      let response = fetch("https://www.gimperservices.com:8099/login", {
          method: "POST" ,
          timeoutInterval: 20000, // milliseconds
        //  disableAllSecurity: true,

          body:   JSON.stringify(objects),
          sslPinning: {
            certs: ["www.gimperservices.com"] // your certificates name (without extension), for example cert1.cer, cert2.cer
          },
          headers: {
              Accept: "application/json", 
              'Content-Type': 'application/json'  ,
          },
      }).then((response) => response.json())
          .then((json) => {
            console.log(json)
            if(json.status ==="Login success"){}

**Comment by layeng** [comment]
Hi
Just saw that the thread is closed but if anyone has the answer, I would be very grateful if you can help out. Thanks

**Comment by martabacc** [comment]
Hi, does using  publicKey pinning also needs cert?
I saw the docs,in snippets of publicKey pinning it still mentions providing certs.

I always got error of SSLContext is not initialized. Need help @MaxToyberman 
using RN 0.59 rn-ssl-pinning 1.1.3

**Comment by martabacc** [comment]
[fixed] I was scouring through `public key` related issues in the repo and found the author mentioned publicKey support was added at v.1.4.0 (a changelog could make this easier) then I update to 1.4.0

the problem was it uses androidx for one single import (androidx.annotation.NonNull) and my project don't support androidx, so I change it manually and it works.

**Comment by layeng** [comment]
I added using private key. I changed the format from xxx.crt to xxx.cer for android and for ios, i changed it to xxx.der (binary version) but still call it xxx.cer. For the rest, I just follow instructions from MaxToyberman and it works. I didn't get it right earlier because I use the cert www.gimperservices.com when it should have been www_gimperservices_com. If you have problems with private key implementation, do let me know. I prefer to use public key. Will try that next. I am using it for react-native app. Hope you don't mind if I ask you when I have problems. Thanks for writing to me. I always feel very alone in the internet universe.

**Comment by iaxelrad** [comment]
> 
Hey, I would love some help with the private key issue. I got a pfx file that i converted to cer and tried to use, but am getting a SSLContext is not initialised.

**Comment by Princejain21** [comment]
> > 
> 
> Hey, I would love some help with the private key issue. I got a pfx file that i converted to cer and tried to use, but am getting a SSLContext is not initialised.

hey,
Have you got the solution, Beacause I have also stuck on same place.

**Comment by jgschis** [comment]
> > 
> 
> Hey, I would love some help with the private key issue. I got a pfx file that i converted to cer and tried to use, but am getting a SSLContext is not initialised.


Don't deal with the private key. Just deal with the public key / certificate.  Putting the private key in your anroid app will compromise your website/whatever it's protecting.

**Comment by jgschis** [comment]
I got this error when putting the sha256 of the public key in the array. I actually have no idea what the format is. Is there supposed to be a slash after the name of the hash algorithm (sha256)?
