### ISSUE TITLE
Unclear error message when certificate is expired or invalid

### ISSUE THREAD

**Issue by vinithreddy3** [MaxToyberman/react-native-ssl-pinning#33]
When I pin invalid/expired certificate in the fetch I see the error message as below : 

 '' java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. ''
which is not providing proper details on why the certificate pinning failed. It would be great if a more proper message will be shown...

**Comment by MaxToyberman** [comment]
@vinithreddy3 i'm not showing the error, the error comes from okhttp3. i don't think that i can change the error message

**Comment by vinithreddy3** [comment]
Oh, Thanks for the quick response.

**Comment by MaxToyberman** [comment]
@vinithreddy3 sure :)
