### ISSUE TITLE
unable to post request with form data. error: "Method POST must have request body".

### ISSUE THREAD

**Issue by asusual1540** [MaxToyberman/react-native-ssl-pinning#34]
I have successfully connected with my server with get request. But having trouble with post request with formData. 

let data = new FormData()
        let words = (image["uri"].split("/"))
        data.append('sampleFile',
            {
                name: words[words.length - 1],
                type: image["type"],
                uri: image["uri"]
            })
        let url = 'https://mydomain.com/upload/'
        fetch(url, {
            method: "POST",
            body: data,
            sslPinning: {
                certs: ["mycert"]
            }
        })
        .then(res => console.log(res))
        .catch(err => console.log(err))

**Comment by MaxToyberman** [comment]
Hi @asusual1540  did you read this part ? 
`https://github.com/MaxToyberman/react-native-ssl-pinning#multipart-request-formdata`
'sampleFile' should be file and your body is wrong too

**Comment by MaxToyberman** [comment]
Closing this issue, reopen if you find a problem
