### ISSUE TITLE
Unable to request using FormData

### ISSUE THREAD

**Issue by castalonirenz** [MaxToyberman/react-native-ssl-pinning#38]
Hi MaxToyberman, i really need your help how to use formData in your library. when im having a request theres an error with ios when using formData

   var photo = {
              uri: Platform.OS == "android" ? response.uri : response.uri.replace("file://", ""),
              type: "image/png",
              name: response.name
            }

            var data = new FormData();
            data.append('token', this.props.token);
            data.append('id', this.props.Credentials.id);
            data.append('image', photo);

body = {
 formData: JSON.stringy(data)
}

is there any wrong with these?

**Comment by MaxToyberman** [comment]
@castalonirenz i don't think that you need the JSON.stringify, what is the error you get ?

**Comment by castalonirenz** [comment]
There is an error in IOS here is the error:

![image](https://user-images.githubusercontent.com/13584669/75306599-7cbe6000-5884-11ea-8057-d2d937465110.png)


and here is my code:

  ImageResizer.createResizedImage(imgResponse.uri, 720, 1080, 'JPEG', 100)
          .then(async (response) => {

            var photo = {
              // uri: Platform.OS == "android" ? response.uri : response.uri.replace("file://", ""),
              uri: require("../../src/assets/icon/Add.png"),
              type: "image/png",
              name: "test"
            }

            let data = new FormData();
            data.append('token', this.props.token);
            data.append('id', this.props.Credentials.id);
            data.append('image', photo);

        let uploadImage = await ImageApiRequest("user/update_user_img", "POST", data, null)

and here is the SSL Pinning 

![image](https://user-images.githubusercontent.com/13584669/75306677-b2fbdf80-5884-11ea-990f-f621c4da0ea8.png)

**Comment by MaxToyberman** [comment]
@castalonirenz  the problem is with this :

```
var photo = {
       // uri: Platform.OS == "android" ? response.uri : response.uri.replace("file://", ""),
       uri: require("../../src/assets/icon/Add.png"),
       type: "image/png",
       name: "test"
}

data.append('image', photo);
```
Try this: 

```
var photo = {
       uri: encodeURIComponent(response.uri),
       type: "image/png",
       fileName: "test"
      data:  fileDataInBase64
}

data.append('file', photo);
```
uri can be used only on android, for ios you need to add base64 of the file , you must add the file with the key file as stated in docs, Hope this helps you.

**Comment by castalonirenz** [comment]
Thank you will try this

**Comment by castalonirenz** [comment]
Still not working

![image](https://user-images.githubusercontent.com/13584669/75329233-43a0e280-58ba-11ea-8048-411238c562b9.png)

![image](https://user-images.githubusercontent.com/13584669/75329255-4dc2e100-58ba-11ea-82d2-a70480d5c6ba.png)



here is the error 
![image](https://user-images.githubusercontent.com/13584669/75329315-64693800-58ba-11ea-997b-e50fc21996cb.png)

**Comment by MaxToyberman** [comment]
@castalonirenz  do you take the image from the gallery ?

**Comment by castalonirenz** [comment]
@MaxToyberman yes im using react native image picker

**Comment by MaxToyberman** [comment]
@castalonirenz try filename instead of name.

**Comment by castalonirenz** [comment]
will try that thank you Mr @MaxToyberman

**Comment by MaxToyberman** [comment]
@castalonirenz did it work ?

**Comment by castalonirenz** [comment]
Sorry for the late response this is still not working

here is the formData
![image](https://user-images.githubusercontent.com/13584669/95417689-3972b680-0968-11eb-9c5b-fa87d9d4b1ec.png)

and here is the request
![Uploading image.png…]()

**Comment by castalonirenz** [comment]
i know the problem the value must be in string not integer for example in the id.

but here another one the formData token is not being read/accepted by the backend it always return invalid token but when im using axios with the same formData it works like a charm kindly check it. i really like this library because of the SSL Feature
