### ISSUE TITLE
IOS public key pinning - Error: cancelled

### ISSUE THREAD

**Issue by sylv1b** [MaxToyberman/react-native-ssl-pinning#40]
I followed the guide and it works fine with android. However, it doesn't works with IOS. I tried GET and POST request, but I always get "Cancelled" as error. 
I even tried to request other domains, but as said, nothing works.
My config is RN 0.61.5 and react-native-ssl-pinning ^1.4.0

**Comment by MaxToyberman** [comment]
@sylv1b i need more information, cancelled means that the something is wrong with the certificate, because android uses the sha256 hash's, did you add your certificates to the ios project ?
can you give me your domain name ?

**Comment by sylv1b** [comment]
hi, I added the certificate to IOS. My domain name is api.edchild.com.

**Comment by MaxToyberman** [comment]
@sylv1b do you have a redirect ?

**Comment by MaxToyberman** [comment]
@sylv1b found the problem ! 
run this command and take the first certificate:
let me know if this works for you 

openssl s_client -showcerts -servername api.edchild.com -connect api.edchild.com:443 </dev/null

**Comment by sylv1b** [comment]
Hi, it works now! Thank you!

**Comment by martabacc** [comment]
Hi, does it still needs certificate if we use public key pinning?

**Comment by cengit** [comment]
> Hi, does it still needs certificate if we use public key pinning?

yes it needs for iOS. 
I think the iOS will need to pick it automatically from .cer file. if you don't put the .cer file to the project, where does it pick.

For android: I think no. cuz it will direct read the publick-key from the certificates array. example:
```ts
sslPinning: {
      certs: [
        'sha256/WgoPGXU0SpJ4q65+D5dMK3VNJY9N3ZE9Hi5nVtcGh6I=',
      ],
    },
```

please correct me if I'm wrong @MaxToyberman
