### ISSUE TITLE
IOS Certificate Pinning - Error object cannot be nil

### ISSUE THREAD

**Issue by varian1** [MaxToyberman/react-native-ssl-pinning#41]
Hi  @MaxToyberman , 

I need yor help.
I followed the guide and it works fine with android. However, it doesn't works with IOS. I tried GET and POST request, but I got this native error 

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'

I try to debug then it's stopped here
<img width="965" alt="Screen Shot 2020-02-27 at 09 23 49" src="https://user-images.githubusercontent.com/16277093/75406511-34b24280-5943-11ea-82de-566378887b0a.png">
I don't know what's missing here

My config is RN 0.58.3 and react-native-ssl-pinning 1.4.0

**Comment by MaxToyberman** [comment]
Hi @varian1 can you show me your request ?

**Comment by varian1** [comment]
<img width="538" alt="Screen Shot 2020-02-27 at 13 28 27" src="https://user-images.githubusercontent.com/16277093/75418078-21b06a00-5965-11ea-9254-47f0314ca755.png">

**Comment by MaxToyberman** [comment]
@varian1  can you show me the request code ?

**Comment by varian1** [comment]
const request= {
      body:data,
      headers: {
        ...headers,
        'Cache-Control': 'no-cache no-store',
      },
      method: method,
      sslPinning: {
        certs: ['certificate'],
      },
      timeoutInterval: 60000,
    };

    method === GET && delete payload['body'];

    return fetch(url, { ...request})
      .then(res => {
        return JSON.parse(res.bodyString);
      })
      .catch(exception => {
        console.error(exception);
      });

**Comment by MaxToyberman** [comment]
@varian1  what is payload ?

**Comment by varian1** [comment]
sorry, It's request actually

**Comment by MaxToyberman** [comment]
@varian1 I assume you are trying the GET method right ?

**Comment by varian1** [comment]
Yes @MaxToyberman

**Comment by MaxToyberman** [comment]
@varian1 I cant reproduce it. need to debug it.

**Comment by MaxToyberman** [comment]
@varian1 did you solve the issue ?

**Comment by MaxToyberman** [comment]
@varian1  please reopen if needed

**Comment by vinodkumarch** [comment]
[__NSArrayM insertObject:atIndex:]: object cannot be nil

**Comment by vinodkumarch** [comment]
Hi @MaxToyberman I am getting this issue for iOS when I was integrated ssl pinning in react native
