### ISSUE TITLE
How to handle POST Query using FormData

### ISSUE THREAD

**Issue by wibes** [MaxToyberman/react-native-ssl-pinning#45]
I tried using FormData given in repository but did not worked for me. I was not getting any response , means no call in then or catch . 

I want to use 

const data = new FormData();
  data.append("query", queryString);

**Comment by MaxToyberman** [comment]
let formData = new FormData()

formData.append('query', queryString);

fetch(url, {
	method: "POST" ,
	timeoutInterval: communication_timeout, // milliseconds
	body: {
	    formData,
	},
	sslPinning: {
		certs: ["cert1","cert2"]
	},
	headers: {
		'content-type': 'multipart/form-data; charset=UTF-8',
		accept: 'application/json, text/plain, /',
	}
})

**Comment by wibes** [comment]
I tried this but did not got any response in react native, but I checked native iOS code and found that it is throwing an error 

rror Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: forbidden (403)" UserInfo={NSLocalizedDescription=Request failed: forbidden (403), NSErrorFailingURLKey=https://

**Comment by wibes** [comment]
Whereas it is working fine in android. Please reply asap

**Comment by wibes** [comment]
May be issue is with AFNetworking

**Comment by MaxToyberman** [comment]
@wibes  can you send me the request ? so i can debug it on my side ?

**Comment by wibes** [comment]
Can't share the request, is there any other way round. Can you update AFNetworking ?

**Comment by wibes** [comment]
@MaxToyberman

**Comment by MaxToyberman** [comment]
@wibes it is working for me both on android and ios, you can debug it if you cant share the request.
