### ISSUE TITLE
post request is cancelled

### ISSUE THREAD

**Issue by Gaganesh** [MaxToyberman/react-native-ssl-pinning#48]
@MaxToyberman , i am using version 1.4.0 
                                my post request is cancelled with sslPinning. i am using certificate in .der 
                               format.

**Comment by MaxToyberman** [comment]
@Gaganesh  its a certificate mismatch.

**Comment by JoelOnGithub** [comment]
When iOS returns "cancelled" it means the certificate is not right. Did you restart the app after installing the certificate?

**Comment by Gaganesh** [comment]
@MaxToyberman
I got .pfx format certificate from my server team and i run the following command to get .der format.
openssl pkcs12 -in certificate.pfx -out certificate.der -nokeys -clcerts 
it gives me .der format certificate.

but when i put .cer format certificate in xcode then it crashes very first.

@JoelOnGithub  yes i restarted but the problem is same it always gives "cancelled" error.

**Comment by MaxToyberman** [comment]
@Gaganesh do this steps please :  (replace with your server name)

1)openssl s_client -showcerts -servername google.com 1.-connect google.com:443 </dev/null

2)Copy the certificate (Usally the first one in the chain), and paste it using nano or other editor like so , nano mycert.pem

3)convert it to .cer with this command openssl x509 -in mycert.pem -outform der -out mycert.cer

**Comment by Gaganesh** [comment]
@MaxToyberman , Thanks a lot.. above steps worked for me
