### ISSUE TITLE
error on android at application startup - first few requests

### ISSUE THREAD

**Issue by dimlksin2** [MaxToyberman/react-native-ssl-pinning#52]
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by dimlksin2** [comment]
please help me fix this error - I use all the latest versions

**Comment by MaxToyberman** [comment]
@dimlksin2 How did you generate the certificate ?

**Comment by dimlksin2** [comment]
> @ dimlksin2 Как вы сгенерировали сертификат?

openssl s_client -showcerts -connect google.com:443

Copy the certificate (Usally the first one in the chain), and paste it using nano or other editor like so , nano mycert.pem

convert it to .cer with this command openssl x509 -in mycert.pem -outform der -out mycert.cer

**Comment by MaxToyberman** [comment]
@dimlksin2  this is the the old commands. I have updated the readme.
Just follow this new instructions :
https://github.com/MaxToyberman/react-native-ssl-pinning#create-the-certificates

feel free to contact me if you still need help.

**Comment by dimlksin2** [comment]
I'm sorry, but the command is not executed

openssl s_client -showcerts -servername google.com 1.-connect google.com:443 </dev/null

s_client: Use -help for summary.

**Comment by dimlksin2** [comment]
> @dimlksin2 this is the the old commands. I have updated the readme.
> Just follow this new instructions :
> https://github.com/MaxToyberman/react-native-ssl-pinning#create-the-certificates
> 
> feel free to contact me if you still need help.

I'm sorry, but the command is not executed

openssl s_client -showcerts -servername google.com 1.-connect google.com:443 </dev/null

s_client: Use -help for summary.

**Comment by MaxToyberman** [comment]
@dimlksin2  run this: 
openssl s_client -showcerts -servername google.com -connect google.com:443 </dev/null

replace google.com with yours.

**Comment by MaxToyberman** [comment]
@dimlksin2 did it work ?

**Comment by AndersonHqds** [comment]
I'm having the same error

React Native - 0.61.4
React Native SSL Pinning - ^1.4.8

------
I've generated the google cert to test with
- openssl s_client -showcerts -servername google.com -connect google.com:443 </dev/null\

Adding the cert to a PEM file using nano and converting the .pem to .cer with the command: 
- openssl x509 -in glg.pem -outform der -out glg.cer

After that I copy the glg.cer to /android/app/src/main/assets, and call it using the fetch from react-native-ssl-pinning

fetch('https://google.com/', { method: 'GET', sslPinning: { certs: ['glg'] } }).then(result => console.log(result)).catch(console.log);

But I receive the error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

----
Could you help me? @MaxToyberman
