### ISSUE TITLE
How to bypass ssl pinning

### ISSUE THREAD

**Issue by iamsubhaa** [MaxToyberman/react-native-ssl-pinning#53]
How I bypass ssl pinning

**Comment by MaxToyberman** [comment]
@iamsubhaa  currently this is not supported, a pr is welcome.

**Comment by jameskitt** [comment]
I would need a bypass for SSL Pinning too.

**Comment by MaxToyberman** [comment]
@iamsubhaa new version 1.4.5 was release with an option to disable ssl pinning for request, just add a property disableAllSecurity=true, you can see an example in the docs
