### ISSUE TITLE
How to use react native ssl pinning with axios library 

### ISSUE THREAD

**Issue by bhuvin25** [MaxToyberman/react-native-ssl-pinning#54]
How to use react native ssl pinning with axios library

**Comment by MaxToyberman** [comment]
@bhuvin25 , What are you trying to acheive ?

**Comment by bhuvin25** [comment]
@MaxToyberman I need to implement Certificate Pinning in my react native app which uses axios for api call

**Comment by MaxToyberman** [comment]
@bhuvin25 and how is it related to react-native-ssl-pinning ?

**Comment by bhuvin25** [comment]
@MaxToyberman your library react-native-ssl-pinning has ssl pinning property in fetch method, so as i am using axios library for api call  i need to know is it possible to have certificate pinning through your library in react native

**Comment by MaxToyberman** [comment]
@bhuvin25 react-native-ssl-pinning is not based on axios, i am not sure i understand the question

**Comment by olie-chan** [comment]
@MaxToyberman I think he means does the underlying certificate pinning work if you use a different network client than the `fetch` provided from `react-native-cert-pinner`. My guess is that if you use [axios](https://github.com/axios/axios) which uses XmlHttpRequests under the hood that it doesn't ?

**Comment by MaxToyberman** [comment]
@olie-chan If you use other client like axios, you will not have ssl pinning for this request

**Comment by olie-chan** [comment]
Thanks @MaxToyberman ! This is actually a problem that I'm looking at since we've used axios throughout the app but we need to add ssl-pinning. Do you happen to know if using Trustkit on the native side would enable me to use axios client side ? I've been looking at this article for reference https://medium.com/@jaedmuva/react-native-ssl-pinning-is-back-e317e6682642

**Comment by CarlosLevir** [comment]
Any update about this @olie-chan? Did you solve it?

**Comment by CarlosLevir** [comment]
Any update about this? Did you solve it? @olie-chan @bhuvin25

**Comment by olie-chan** [comment]
@CarlosLevir I ended up just using the native trustkit library on both ios and android which **does** work with axios in React native. You have to add a bit of code to the native ios/android side but it's just a one time thing. You can check out the docs [here](https://github.com/datatheorem/TrustKit)

**Comment by CarlosLevir** [comment]
Awesome. Thank you @olie-chan!

**Comment by Georgge** [comment]
@olie-chan so the fact of installing TrustKit natively, does axios take the certificate to do the pinning?

**Comment by murtazakaz** [comment]
> Thanks @MaxToyberman ! This is actually a problem that I'm looking at since we've used axios throughout the app but we need to add ssl-pinning. Do you happen to know if using Trustkit on the native side would enable me to use axios client side ? I've been looking at this article for reference https://medium.com/@jaedmuva/react-native-ssl-pinning-is-back-e317e6682642
> 
> Edit: Add Trustkit to the native side and it will work fine with axios

hey can you walkthrough what changes you have implmented on react native axios side?

**Comment by sujitnair3541** [comment]
@murtazakaz 
I was able to enable SSL pinning on the iOS part for my React Native Application using [TrustKit](https://github.com/datatheorem/TrustKit).
I am using Axios to make server interactions. 
There are two ways to implement TrustKit, by code or by using Info.plist. I have done using the Info.plist and you can find the implementation for the same below: 
1. Add and install TrustKit in your podfile. (`pod 'TrustKit'`) 
2. Open your Info.plist as Source Code add the below code to it.

>
    <key>TSKConfiguration</key>
	<dict>
		<key>TSKSwizzleNetworkDelegates</key>
		<true/>
		<key>TSKPinnedDomains</key>
		<dict>
			<key>yourDomain.com</key>
			<dict>
				<key>TSKPublicKeyHashes</key>
				<array>
					<string>public key 1</string>
					<string>public key 2</string>
				</array>
				<key>TSKPublicKeyAlgorithms</key>
				<array>
					<string>TSKAlgorithmRsa2048</string>
				</array>
				<key>TSKIncludeSubdomains</key>
				<true/>
				<key>TSKEnforcePinning</key>
				<true/>
			</dict>
		</dict>
	</dict>

**Important things to note:**
1. `TSKSwizzleNetworkDelegates` needs to be set to true.
2. `yourDomain.com` is the base URL for your API.
3. `public Key 1` and `public Key 2` are the public keys for your API. You can get the pubic keys for any public domain [here](https://www.ssllabs.com/ssltest/)
4. `TSKEnforcePinning` can be used to enable / disable SSL pinning by setting it to `true` / `false` respectively. (Incase you wish to enable/disable it temporarily)
5. For more details, please check out [TrustKit Documentation](https://datatheorem.github.io/TrustKit/documentation/Classes/TrustKit.html)

I hope this helps.

**Comment by yorickshan** [comment]
> @murtazakaz
> I was able to enable SSL pinning on the iOS part for my React Native Application using [TrustKit](https://github.com/datatheorem/TrustKit).
> I am using Axios to make server interactions.
> There are two ways to implement TrustKit, by code or by using Info.plist. I have done using the Info.plist and you can find the implementation for the same below:
> 
> 1. Add and install TrustKit in your podfile. (`pod 'TrustKit'`)
> 2. Open your Info.plist as Source Code add the below code to it.
> 
> > 
> 
> ```
> <key>TSKConfiguration</key>
> <dict>
> 	<key>TSKSwizzleNetworkDelegates</key>
> 	<true/>
> 	<key>TSKPinnedDomains</key>
> 	<dict>
> 		<key>yourDomain.com</key>
> 		<dict>
> 			<key>TSKPublicKeyHashes</key>
> 			<array>
> 				<string>public key 1</string>
> 				<string>public key 2</string>
> 			</array>
> 			<key>TSKPublicKeyAlgorithms</key>
> 			<array>
> 				<string>TSKAlgorithmRsa2048</string>
> 			</array>
> 			<key>TSKIncludeSubdomains</key>
> 			<true/>
> 			<key>TSKEnforcePinning</key>
> 			<true/>
> 		</dict>
> 	</dict>
> </dict>
> ```
> 
> **Important things to note:**
> 
> 1. `TSKSwizzleNetworkDelegates` needs to be set to true.
> 2. `yourDomain.com` is the base URL for your API.
> 3. `public Key 1` and `public Key 2` are the public keys for your API. You can get the pubic keys for any public domain [here](https://www.ssllabs.com/ssltest/)
> 4. `TSKEnforcePinning` can be used to enable / disable SSL pinning by setting it to `true` / `false` respectively. (Incase you wish to enable/disable it temporarily)
> 5. For more details, please check out [TrustKit Documentation](https://datatheorem.github.io/TrustKit/documentation/Classes/TrustKit.html)
can you tell me how to get a backup pin? I can only get one public Key now at https://www.ssllabs.com/ssltest/

**Comment by satheeshwaran** [comment]
@sujitnair3541 TrustKit is only available for iOS, what about Android?

**Comment by gabrielmoncea** [comment]
I think you can use TrustKit-Android made by the same developer
https://github.com/datatheorem/TrustKit-Android

**Comment by yogendrajs** [comment]
Hi @sujitnair3541 , how did you check if the TrustKit is working for certificate-pinning. Actually, I had also implemented the same, but even with the wrong public-key hashes, it's working fine for me. Don't know what's going wrong.

**Comment by sandeepg1220** [comment]
Yes me also implemented the same but how to check this whether it is working or not.

**Comment by mkdesilva** [comment]
> Yes me also implemented the same but how to check this whether it is working or not.

@sandeepg1220 If it's working correctly, you can change the hashes in your TSKPublicKeyHashes so that they are **incorrect**. 
Then, build and run your app and your network connections should be getting terminated.

**Comment by yogendrajs** [comment]
> Yes me also implemented the same but how to check this whether it is working or not.

@sandeepg1220 try with the wrong key-hashes, it must fail sending any request. If it doesn't, then something's wrong there. Also, if you're using Xcode, you must see the logs saying whether it's succeeded or not.

**Comment by sandeepg1220** [comment]
Already tried with wrong key-hashes but it's working fine @yogendrajs @mkdesilva

**Comment by mkdesilva** [comment]
> Already tried with wrong key-hashes but it's working fine @yogendrajs @mkdesilva

@sandeepg1220 Then I would try verify that the correct domains are configured in your TSKPinnedDomains

**Comment by sandeepg1220** [comment]
```
<key>TSKConfiguration</key>
	<dict>
		<key>TSKPinnedDomains</key>
		<dict>
			<key>domain.com</key>
			<dict>
				<key>TSKEnforcePinning</key>
				<true/>
				<key>TSKIncludeSubdomains</key>
				<true/>
				<key>TSKPublicKeyAlgorithms</key>
				<array>
					<string>TSKAlgorithmRsa2048</string>
				</array>
				<key>TSKPublicKeyHashes</key>
				<array>
					<string>XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</string>
					<string>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</string>
				</array>
			</dict>
		</dict>
	</dict>
```
The above code i'm using in info.plist file. In pod file added pod ‘TrustKit’. My react-native version is 0.63.4
Is there any other changes??

**Comment by sandeepg1220** [comment]
@mkdesilva  Yes I have verified the domain using [](https://www.digicert.com)

**Comment by mkdesilva** [comment]
```
<key>TSKSwizzleNetworkDelegates</key>
<true/>
```

@sandeepg1220  Have you included this entry?

**Comment by sandeepg1220** [comment]
@mkdesilva  Yes I have checked with TSKSwizzleNetworkDelegates also same here

**Comment by rahulunni73** [comment]
A similar problem, used wrong key-hashes but the still axios working fine, ios

**Comment by softopia-tech** [comment]
@rahulunni73 @fwdenis check this https://itnext.io/react-native-security-ssl-pinning-cde086210d58
this article also mentioned why the pinning is working with wrong key

**Comment by rahulunni73** [comment]
@softopia-tech  thanks

**Comment by Eliajn** [comment]
@olie-chan the library that you shared only works for IOS? what did you do to make it work for android?

**Comment by efajardolopez** [comment]
@Eliajn for android check this https://medium.com/@jaedmuva/react-native-ssl-pinning-is-back-e317e6682642
