### ISSUE TITLE
Error SSLContext is not initialized

### ISSUE THREAD

**Issue by hanifmhd** [MaxToyberman/react-native-ssl-pinning#56]
i got error "SSLContext is not initialized" when implement certificate pinning in Android
<img width="429" alt="Screen Shot 2020-04-22 at 08 14 17" src="https://user-images.githubusercontent.com/15220788/79931294-e918a280-8474-11ea-82e8-490554518f44.png">

**Comment by MaxToyberman** [comment]
@hanifmhd  can you show me the request ?

**Comment by gersonlimadev** [comment]
@hanifmhd I had this same issue, you should to put the certificates in android/app/src/main/assets

**Comment by MaxToyberman** [comment]
@hanifmhd  @gersonlimadev  is right, reopen if needed please.

**Comment by ChameeraFortuna** [comment]
I have the same issue.

- Certificate path is ok

- No .cer extensions in code

**Comment by MaxToyberman** [comment]
@ChameeraFortuna  can you show me your config ?

**Comment by ChameeraFortuna** [comment]
@MaxToyberman 
`fetch('https://testurlserver.lk/corporate-ws', {
        method: options.method,
        timeoutInterval: 50000, // milliseconds
        body: null,
        sslPinning: {
          certs: ["cert_one", "cert2020"] 
        },
        headers: options.headers,
      }).then(response => {
        return response;
      })
      .then(json => resolve(json))
      .catch(reject)`

```
react-native : v0.60.5
react-native-ssl-pinning: 1.4.6
```

**Comment by MaxToyberman** [comment]
@ChameeraFortuna remove the body: null

**Comment by ChameeraFortuna** [comment]
@MaxToyberman Didn't resolve the error without null. Using wrong certificate it comes correct error message ("Unacceptable certificate: CN=DigiCert Global Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US"). this issue comes with correct certificate

**Comment by MaxToyberman** [comment]
@ChameeraFortuna  so now you get another error ?

**Comment by ChameeraFortuna** [comment]
No Same Issue

**Comment by MaxToyberman** [comment]
@ChameeraFortuna  can you please check if issue exists in 1.4.5 ?

**Comment by MaxToyberman** [comment]
@ChameeraFortuna Did you run react-native run android after putting it in assets ? 
Just checked this request, works locally :

```
    fetch('https://testurlserver.lk/corporate-ws', {
      method: 'GET',
      timeoutInterval: 50000,
      sslPinning: {
        certs: ['cert_one', 'cert2020'],
      },
      headers: headers,
    })
```

**Comment by ChameeraFortuna** [comment]
Yes, First I put certificate to assets and then run the application. I used working certificate in Native Android in react-native but I occurred the same issue.
