### ISSUE TITLE
timeout in public key pinning

### ISSUE THREAD

**Issue by anchaljain123** [MaxToyberman/react-native-ssl-pinning#57]
I am using public key pinning in my project

RN: 0.61.5
react-native-ssl-pinning: "^1.4.0",

Response: 
> failed to connect to ext-qamobile3-aws1.freecharge.in/54.208.151.241 (port 443) from /192.168.232.2 (port 59100) after 15000ms

**Comment by MaxToyberman** [comment]
@anchaljain123  android or ios ? or both ?
