### ISSUE TITLE
[__NSArrayM insertObject:atIndex:]: object cannot be nil

### ISSUE THREAD

**Issue by vinodkumarch** [MaxToyberman/react-native-ssl-pinning#60]
in iOS I am getting this issue and app crashed due to this thread

**Comment by MaxToyberman** [comment]
@vinodkumarch need more info, show me your request please

**Comment by vinodkumarch** [comment]
let result = await fetch(baseUrl + 'login', {
			method: "POST",
		//	timeoutInterval: 10000,
			sslPinning: {
			  certs: sslPinningKey
			},
			headers: {
				'Content-Type': 'application/json'
			},
			body: JSON.stringify({
				sdfdsf: dfsfsf,
				dffsfs: sdfsdfdsf,
				deviceToken: deviceToken,
			})
		});
		return this.checkResultData(result)

**Comment by MaxToyberman** [comment]
@vinodkumarch try to add pkPinning

**Comment by vinodkumarch** [comment]
Hi @MaxToyberman after adding pkPinning:true I am getting below error

Task <073D006C-63B4-4B26-9F2D-A32E16BC6D0C>.<1> HTTP load failed, 0/0 bytes (error code: -999 [1:89])

May I know the reason for this

**Comment by MaxToyberman** [comment]
@vinodkumarch  your keys should begin with sha256 like this :

`export const sslPinningKey = ["sha256/dsfsdRrAn7JKnbQG/uEtLMkBgFF2Fuihg=","sha256/12M0N0iCTTq5lZpY/1TL0siVICTuMg=","sha256/y3Qdfsdfsdffh/lJ7ZbmW2CckvPhue0="]
`

**Comment by MaxToyberman** [comment]
@vinodkumarch how did you get the keys  for android ? did you add the certs to the ios project ?

**Comment by vinodkumarch** [comment]
Yes @MaxToyberman I got the keys from by backend team 

As well as I have one .cer file to the project and also copied to bundle resources in iOS and android also same certificate imported.

**Comment by MaxToyberman** [comment]
@vinodkumarch did you create them in der format ?

try to follow this : 
https://github.com/MaxToyberman/react-native-ssl-pinning#usage

**Comment by MaxToyberman** [comment]
@vinodkumarch  did it work ?

**Comment by MaxToyberman** [comment]
@vinodkumarch please reopen if needed
