### ISSUE TITLE
Error: undefined is not a function (near '...(0, _reactNativeSslPinning.default)...')

### ISSUE THREAD

**Issue by davideparlapiano** [MaxToyberman/react-native-ssl-pinning#61]
Has someone encountered this error? Error  undefined is not a function (near '...(0, _reactNativeSslPinning.default)...')

**Comment by MaxToyberman** [comment]
@davideparlapiano which version do you use ? and react-native version

**Comment by MaxToyberman** [comment]
@davideparlapiano  reopen if needed
