### ISSUE TITLE
Getting "Cancelled" only on iOS, but working on Android (same certificates)

### ISSUE THREAD

**Issue by strawberry-code** [MaxToyberman/react-native-ssl-pinning#62]
Library linked correctly.

Working on Android, but on iOS is still get cancelled even if I use the same certificates used in Android.

"react-native-ssl-pinning": "^1.4.1",
```
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 694.13 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-R | Google APIs Intel x86 Atom_64, android-R | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.13.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-create-library: 3.1.2
```

**Comment by MaxToyberman** [comment]
@strawberry-code which command did you run to generate the certs ?

**Comment by strawberry-code** [comment]
Hi @MaxToyberman!

I am using this command:

```
openssl s_client -servername web.site.one.com -connect web.site.one.com:443 | openssl x509 -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64
```

I use the same hash both for Android and both for iOS.

**Comment by MaxToyberman** [comment]
@strawberry-code  i am not sure about this command,
follow my instructions here: 

https://github.com/MaxToyberman/react-native-ssl-pinning#usage

reopen if needed

**Comment by strawberry-code** [comment]
Hi, sorry for reopen this case. 😔

This time I will describe step by step what I do on iOS to use public key pinning.

1. `npm install react-native-ssl-pinning --save`
2. `react-native link react-native-ssl-pinning`
3. `openssl s_client -showcerts -servername my.site.com -connect my.site.com:443 </dev/null`
4. I copy the first certificate from the terminal in the file **mySite.pem**:
```
-----BEGIN CERTIFICATE-----
MIIGoDCCBYigAwIBAgISA0IuQC7pF6+6nSRBYRVfcLxAMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
...
U0ina32j+FjbX+vBe6KJaae+ZwRt4gf1nO40vJR7dpKiV8czFnK37caQVjZ4roGu
qhK6mAodjs+fjZ5wywphCrfPcyg=
-----END CERTIFICATE-----
```
5. ` openssl x509 -in mySite.pem -outform der -out mySite.cer`


**Android**
I follow [these steps](https://github.com/MaxToyberman/react-native-ssl-pinning#android-1) and then I use [Public Key Pinning](https://github.com/MaxToyberman/react-native-ssl-pinning#public-key-pinning) and tested on the App, works fine.

**iOS**
6. dragged **mySite.cer** to Xcode project, marking your target and 'Copy items if needed' (green arrow in the picture below)
![Screenshot 2020-04-29 at 12 30 08](https://user-images.githubusercontent.com/18684103/80586495-55674900-8a15-11ea-8d91-ada4c6b05871.png)
7.  no extra stepsm since AFNetworking will extract the public key from the certificate
<img width="810" alt="Screenshot 2020-04-29 at 12 32 37" src="https://user-images.githubusercontent.com/18684103/80586745-b000a500-8a15-11ea-8e62-50bbd751f626.png">

Working on Android, but not on iOS (getting cancelled).

**Comment by MaxToyberman** [comment]
@strawberry-code , how many certificates you have in the chain ?
