### ISSUE TITLE
Expo project - issue

### ISSUE THREAD

**Issue by davidvuletas** [MaxToyberman/react-native-ssl-pinning#63]
Hello,

I'm facing with issue which was already mention here #46 #19, it is failing on :
`Cannot read property 'fetch' of undefined node_modules/react-native-ssl-pinning/index.js:8:17 in fetch`
On line where is loading NativeModules =>  `const { RNSslPinning } = NativeModules;`

The main concern from me is next:

Is it possible to this library working with expo project ? because of that linking and those stuff ? 

NOTE:
I'm using Expo SDK 37.0.1 which is using RN 0.61
Thanks in advice!

**Comment by MaxToyberman** [comment]
@davidvuletas i never used expo before, need to check it.

**Comment by MaxToyberman** [comment]
@davidvuletas just created an empty expo project, everything works, how did you install it ?
