### ISSUE TITLE
React/RCTDefines.h file not found

### ISSUE THREAD

**Issue by ghena** [MaxToyberman/react-native-ssl-pinning#66]
During a local build on ios I have this error:

/react-native/React/Base/RCTBridgeModule.h:10:9: 'React/RCTDefines.h' file not found

/node_modules/react-native-ssl-pinning/ios/RNSslPinning/RNSslPinning.m:6:9: In file included node_modules/react-native-ssl-pinning/ios/RNSslPinning/RNSslPinning.m:6:

 In file included from /node_modules/react-native-ssl-pinning/ios/RNSslPinning/RNSslPinning.h:4:

I added the library to xcode as requested.
Let me know.
Regards.

**Comment by CoderYLZhang** [comment]
same problem

**Comment by MaxToyberman** [comment]
@ghena @CoderYLZhang  which react native versions are you using ?

**Comment by Sangkwun** [comment]
Same issue occurred with react native 0.72.6.
