### ISSUE TITLE
Multipart request (FormData) not work in iOS

### ISSUE THREAD

**Issue by canhtran10** [MaxToyberman/react-native-ssl-pinning#67]
with Android it's working perfectly, i don't understand why it's not working in iOS (all ios version), don't have any parameters transfer to the API server:

### **THE LOG REQUEST IN SERVER:**
`Files: ""  ; group receipents: ""  ; User receipients: ""`

### **The CODE:**
```
const localUploadAttachment = async (url, a, message) => {
    let formData = new FormData();
    let dataObj = {
        name: a.name,
        type: 'image/jpg',
        uri: a.uri
    };
    formData.append('files', dataObj); // i tested with "file" parametter but its still not work
    formData.append('groupRecipients', JSON.stringify(message.GroupRecipients));
    formData.append('userRecipients', JSON.stringify(message.UserRecipients));

    let response  = fetch(url, {
	method: "POST" ,
	timeoutInterval: 30000,
	body: {
	      formData: formData,
	},
	sslPinning: {
	      certs: ["mycert1"]
	},
	headers: {
		'content-type': 'multipart/form-data; charset=UTF-8',
		accept: 'application/json, text/plain, /',
	}
    })

    return response;
}
```
### **The LOG API REQUEST:**

![log-api-request](https://user-images.githubusercontent.com/4555599/83220017-0fc8a800-a19c-11ea-90de-46f24ae08137.png)

Please take a look and let me know if you have anything solution for that. Thanks :)

**Comment by MaxToyberman** [comment]
hi @canhtran10 ! it looks good, will need more information to debug it. maybe you can send the full request to my email.
I don't have a way to debug the file upload

**Comment by canhtran10** [comment]
@MaxToyberman i have sent an email to you, please take a look :)

**Comment by MaxToyberman** [comment]
@canhtran10  i saw the video, i know what is the problem. you are attaching an image.
you should send it in base64  (only in iOS)it is written in the docs.
https://github.com/MaxToyberman/react-native-ssl-pinning#multipart-request-formdata

The reason is iOS limitations, i can explain why.

please try to convert is first and tell me if it works :)

**Comment by MaxToyberman** [comment]
@canhtran10 do you use react-native-image-picker ?

**Comment by canhtran10** [comment]
@MaxToyberman yes, I am using react-native-image-picker: 0.26.7

**Comment by MaxToyberman** [comment]
@canhtran10  so in iOS image picker response had data property in it and then : 

    let dataObj = {
        name: a.name,
        type: 'image/jpg',
        uri: 'data:image/jpeg;base64,' + response.data 
    };

**Comment by MaxToyberman** [comment]
@canhtran10 did you check ?

**Comment by canhtran10** [comment]
okie let you know when i have done the checking

**Comment by canhtran10** [comment]
@MaxToyberman 
![image](https://user-images.githubusercontent.com/4555599/84651510-46d8e080-af34-11ea-8786-8bb250d3a9c3.png)
**it is not working for me.** 

Besides, I am using the react-native-document-picker library to upload a document file and it's not working too. 

**There is no data field in DocumentPicker:**
![image](https://user-images.githubusercontent.com/4555599/84651866-d2eb0800-af34-11ea-8d85-e8794b820aed.png)

have a nice day :)

**Comment by MaxToyberman** [comment]
@canhtran10  can you try to use this branch  ?
https://github.com/MaxToyberman/react-native-ssl-pinning#ISSUE-67

if it works i will release a new version

Have a great day :)

**Comment by canhtran10** [comment]
ok @MaxToyberman i will be  trying tomorrow, hope it works :)

**Comment by canhtran10** [comment]
@MaxToyberman it is not working. I am preparing for a new app release, maybe have to exclude the upload function when using react-native-ssl-pinning, and will implement again in the next release. Please take a look at this issue.

**Comment by MaxToyberman** [comment]
@canhtran10 uploaded another fix, please try:  (yarn upgrade the same branch)

let dataObj = {
    name: a.name,
    type: 'image/jpg',
    uri: a.uri,
     data: a.data // this is the data in base64
};

**Comment by canhtran10** [comment]
@MaxToyberman 
![image](https://user-images.githubusercontent.com/4555599/84750793-f28e3900-afe5-11ea-92cb-f423d23f2901.png)

**Comment by MaxToyberman** [comment]
@canhtran10  did you add 'data:image/jpeg;base64,' ? if so remove it

**Comment by castalonirenz** [comment]
still having the same issue

**Comment by MaxToyberman** [comment]
@canhtran10 @castalonirenz  i have just upload some files i know what was the issue : 

1) remove 'content-type': 'multipart/form-data; charset=UTF-8',  from headers.
Setting the Content-Type header manually means it's missing the boundary parameter. Remove that header and allow fetch to generate the full content type. It will look something like this:

2)data: response.data is not needed 

i will update the docs.

your code should look like this : 

```js
     let formData = new FormData();
                  let dataObj = {
                      name: a.name,
                      type: 'image/jpg',
                      uri: a.uri
                  };
                  formData.append('file', dataObj); // i tested with "file" parametter but its still not work
                  formData.append('groupRecipients', JSON.stringify(message.GroupRecipients));
                  formData.append('userRecipients', JSON.stringify(message.UserRecipients));

                  let response  = fetch(url, {
                    method: "POST" ,
                    timeoutInterval: 30000,
                    body: {
                          formData: formData,
                    },
                    sslPinning: {
                          certs: ["mycert1"]
                    }
                      })
```
Please let me know if it worked for you

**Comment by castalonirenz** [comment]
Will try it on monday @MaxToyberman  thanks

**Comment by MaxToyberman** [comment]
@canhtran10  @castalonirenz  did you check it ?

**Comment by castalonirenz** [comment]
@MaxToyberman  i have a question does it automatically set the header to formData even though there is no formData set on the headers?

**Comment by MaxToyberman** [comment]
@castalonirenz yes

**Comment by castalonirenz** [comment]
so both IOS and ANDROID the request will be automatically set to multipart/form-data? so no headers at all to bet set just to be clear

**Comment by MaxToyberman** [comment]
@castalonirenz  you don't need multipart/form-data headers, both on android and iOS

**Comment by castalonirenz** [comment]
Thanks, will try it tomorrow for sure.

**Comment by MaxToyberman** [comment]
@castalonirenz @canhtran10  please reopen if needed

**Comment by castalonirenz** [comment]
![Screen Shot 2020-11-03 at 1 39 46 PM](https://user-images.githubusercontent.com/13584669/97953037-486b4e00-1dda-11eb-8e62-1eebd86d1827.png)

Hi @MaxToyberman  here is the issue without including Multipart on the header

**Comment by castalonirenz** [comment]
![Uploading image.png…]()

**Comment by castalonirenz** [comment]
let params = {
      method: method,
      timeoutInterval: 60000,
      body: {
        formData: formData,
      },
      sslPinning: {
        certs: ['rapids'],
      },
      headers: {
        Authorization: 'Bearer ' + token,
        accept: 'application/json, text/plain, /',
       
      },
    };

**Comment by MaxToyberman** [comment]
@castalonirenz  can you show me your formData ?

**Comment by castalonirenz** [comment]
@MaxToyberman 

![image](https://user-images.githubusercontent.com/13584669/97956288-3b069180-1de3-11eb-93ac-4660d9c50f89.png)

**Comment by MaxToyberman** [comment]
@castalonirenz  
1) remove data: response.uri
2) you shoud send it with 'file' instead of 'image'  (formData.append('file', ....
