### ISSUE TITLE
pkPinning doesn't exist in the Options object.

### ISSUE THREAD

**Issue by criboldi** [MaxToyberman/react-native-ssl-pinning#69]
<img width="752" alt="Screen Shot 2020-06-04 at 2 21 11 PM" src="https://user-images.githubusercontent.com/43180056/83801741-47899100-a66f-11ea-8422-f285a7b2a841.png">
The pkPinning property in the Options object hasn't been added yet so there is an error when setting the options from TypeScript.

**Comment by criboldi** [comment]
<img width="589" alt="Screen Shot 2020-06-04 at 2 27 01 PM" src="https://user-images.githubusercontent.com/43180056/83801931-87507880-a66f-11ea-8339-0c3cd08f4c26.png">

**Comment by MaxToyberman** [comment]
@criboldi Thanks, merged to master and version will be released today.
