### ISSUE TITLE
Unhandled exception when native module returns error string

### ISSUE THREAD

**Issue by AlanLeeMoven** [MaxToyberman/react-native-ssl-pinning#72]
Currently the library throws an unhandled exception for [attempting to assign properties to an error string returned from native modules](https://github.com/MaxToyberman/react-native-ssl-pinning/blob/master/index.js#L21
).

<img width="220" alt="Screen Shot 2020-06-08 at 12 16 19 PM" src="https://user-images.githubusercontent.com/42143955/84055616-179a0080-a983-11ea-9d5e-1980ab1fb770.png">

<img width="220" alt="Screen Shot 2020-06-08 at 12 15 32 PM" src="https://user-images.githubusercontent.com/42143955/84055637-1ec10e80-a983-11ea-9305-2c13c624e515.png">

When I [patched](https://github.com/AlanLeeMoven/react-native-ssl-pinning/commit/3aead381e1385798cec00f43893e52aac4935f20) for my own use, I simply wrapped the assignments in a conditional checking the `typeof data`:

<img width="489" alt="Screen Shot 2020-06-08 at 12 38 42 PM" src="https://user-images.githubusercontent.com/42143955/84057023-0e119800-a985-11ea-8ab8-b66ec09c6639.png">

But allowing the function to return the error string directly violates [the TypeScript response type](https://github.com/AlanLeeMoven/react-native-ssl-pinning/commit/3aead381e1385798cec00f43893e52aac4935f20)

```
    interface Response {
        bodyString: string;
        headers: Header;
        status: number;
        url: string;
        json: () => Promise<{ [key: string]: any}>;
        text: () => Promise<string>;
    }

export declare function fetch(url: string, options: ReactNativeSSLPinning.Options): Promise<ReactNativeSSLPinning.Response>;

```

Would you prefer that the native module error string be incorporated into the existing expected response object, or that the types be modified to conditionally return a Promise-wrapped error string instead?

**Comment by MaxToyberman** [comment]
Hi @AlanLeeMoven I think it would be better to incorporate into the existing expected response object.

Thanks !

**Comment by MaxToyberman** [comment]
Hi ! @AlanLeeMoven anything new ?

**Comment by AlanLeeMoven** [comment]
Hi! Sorry for the delay. Revisited this with a cleaner solution 
https://github.com/MaxToyberman/react-native-ssl-pinning/pull/107

**Comment by MaxToyberman** [comment]
@AlanLeeMoven  Thanks !
