### ISSUE TITLE
Change public key pinned certificates on the fly does not work

### ISSUE THREAD

**Issue by andy-io** [MaxToyberman/react-native-ssl-pinning#73]
Hi,

i am using public key pinning for a domain name. First i inserted wrong key hash , as expected i saw the terminal logcat output of key pin failure. Then i tried to change the pin to correct hash and then reloaded the app. I still see that the library is using the old wrong pin and doesnt respect the new pin i have inserted. This happens also for the example you have shown for public key pinning. Could you help me out ?

Only if i compile the app fully again and re run the app, it respects the new pin otherwise just reloading the app doesnt fix it.

**Comment by MaxToyberman** [comment]
Hi, The okhttp3 is a singleton object and is created when the app is launched.
this is why reload doesnt help. pins are not changed often and i dont think there is a reason to change them on the fly.

**Comment by MaxToyberman** [comment]
@andy-io  why do you need to change it on the fly ?
