### ISSUE TITLE
Store build failing for IOS

### ISSUE THREAD

**Issue by vanso-murlidhar** [MaxToyberman/react-native-ssl-pinning#74]
My normal build is working fine on simulator as well as on device but store build somehow restricting api calls with ssl. 

Without ssl same thing works

**Comment by MaxToyberman** [comment]
@vanso-murlidhar you mean requests are not going out ?

**Comment by vanso-murlidhar** [comment]
> @vanso-murlidhar you mean requests are not going out ?

Correct @MaxToyberman.  If I  use not store build with ssl it works fine

**Comment by MaxToyberman** [comment]
@vanso-murlidhar  i need more information, do you have any errors ? can you show me request info ?

**Comment by vanso-murlidhar** [comment]
getting cancelled from the server. But if it is a certificate issue then it should not work on debug build also. Only release build is failling

**Comment by MaxToyberman** [comment]
@vanso-murlidhar is it the same endpoint both for dev & prod ?

**Comment by vanso-murlidhar** [comment]
servers are Diffrerent

**Comment by MaxToyberman** [comment]
@vanso-murlidhar  so you might need different certs for dev & prod

**Comment by vanso-murlidhar** [comment]
I have  3 certificates for 3 diff. servers and same working for debug builds. only store builds are giving cancelled issue

**Comment by MaxToyberman** [comment]
@vanso-murlidhar cancellled is 100% certificate issue, how did you generate the certificates ?

**Comment by MaxToyberman** [comment]
@vanso-murlidhar did you solve the issue ?

**Comment by bjoernISWG** [comment]
Thanks for your support @MaxToyberman. I found the solution to our problem.
For some reason the certs were not copied during the release build.
Did the following
in xCode: add the certs to **Resources** (via drag), check and copied manually to **Build Phases** > **Copy Bundle Resources**
