### ISSUE TITLE
HTTP load failed, 0/0 bytes in iOS

### ISSUE THREAD

**Issue by strawberry-code** [MaxToyberman/react-native-ssl-pinning#76]
Hi, 

I followed the entire procedure of installation and certificate importing described in the guide of the library.

Unfortunately, I am getting this error:

` Task <CB3108BC-B528-4ADD-AB9D-2666CCE8AC19>.<1> HTTP load failed, 0/0 bytes (error code: -999 [1:89])`

and then I get:

`[warn][tid:com.facebook.react.JavaScript] Possible Unhandled Promise Rejection (id: 0):
"cancelled"`

I looked for the reason of this error, and I found that it could be related to a Metro Bundler caching failure. So, I cleaned and restarted Metro and cleaned (CMD+SHIFT+K) the Xcode project but this didn't solved my problem.

At this point I have no idea on what to do.

Here is my example "test" button I used to test the library:

```
import {fetch as certFetch} from 'react-native-ssl-pinning';

...

 <UserButton text={'Pinning test'} onPress={async () => {
                    console.log(`making certificate pinning test...`)
                    let userinfo = await db.get('userinfo')
 let response = await certFetch('https://mysite.com/ext/authRequests?limit=1&page=1', {
                        method: "GET" ,
                        // your certificates array (needed only in android) ios will pick it automatically
                        sslPinning: {
                            certs: ["mycertname"] // your certificates name (without extension), for example cert1.cer, cert2.cer
                        },
                        headers: {
                            Accept: "application/json; charset=utf-8",
                            "Access-Control-Allow-Origin": "*",
                            "e_platform": "mobile",
                        }
                    })
                    console.log(`response: ${response}`)
  }}/>
```

~~May the `import {fetch as certFetch} from 'react-native-ssl-pinning';` could be the problem?~~
→ We tested with `import {fetch} from 'react-native-ssl-pinning';` the problem still remains.

**Comment by MaxToyberman** [comment]
@strawberry-code Did you add the certificate to xcode ?

**Comment by ayberkanilatsiz** [comment]
same issue and i added to cer file into Xcode.

**Comment by ayberkanilatsiz** [comment]
I fixed the issue.

Place your .cer files in your iOS Project. Don't forget to add them in your Build Phases > Copy Bundle Resources, in Xcode.

**Comment by dnsmob** [comment]
in `AFSecurityPolicy.h`:

> By default, this property is set to any (`.cer`) certificates included in the target compiling AFNetworking. Note that if you are using AFNetworking as embedded framework, no certificates will be pinned by default. Use `certificatesInBundle` to load certificates from your target, and then create a new policy by calling `policyWithPinningMode:withPinnedCertificates`.
> Note that if pinning is enabled, `evaluateServerTrust:forDomain:` will return true if any pinned certificate matches.

I'm sort of assuming (like me) you installed it via Cocoapods, so when AFNetworking is trying to load whatever certificate files it finds, it's using the framework path, not the app, hence not finding the certificates. I guess the solution is to either install the precompiled `.a` manually or try to call those methods above. Even if you do, it implies changing the method `RCT_EXPORT_METHOD(fetch:(NSString *)url obj:(NSDictionary *)obj callback:(RCTResponseSenderBlock)callback) {` in `RNSslPinnning.m`, so you'd be expecting at least a change/fix to this library directly, I think.

I havent cracked it yet, if I manage, I may update things here.

**Comment by Alph4Four** [comment]
Thanks @dnsmob , your insight in the why AFNetworking wasn't able to find the .cer was very helpful.
For me the solution was:
- on your project files tree, select the 'Pods' entry with the blue icon (not the 'Pods' folder);
- with it opened, go to your 'Targets' (left) and search for 'RNSslPinning', select it;
- select 'Build Phases' (tabs on top);
- open 'Copy Bundle Resources';
- click the '+' icon;
- click 'Add Other...';
- go to the path where your .cer is and select it, after that click 'Open';
- AFNetworking will now be able to find your certificate.

I made a PR https://github.com/MaxToyberman/react-native-ssl-pinning/pull/81 with an update to ReadMe so others can find this solution, but I want your feedback on if this works for you too.

**Comment by MaxToyberman** [comment]
@Alph4Four this solution will not work properly, I will fix this issue as part of the library.

**Comment by MaxToyberman** [comment]
@Alph4Four @dnsmob @strawberry-code   versions 1.4.9 was released with the fix.

if you want to see the pr: 
https://github.com/MaxToyberman/react-native-ssl-pinning/pull/84

Please reopen if you have sill issues
