### ISSUE TITLE
Passing parameters in GET request

### ISSUE THREAD

**Issue by annkiitagrawaal-gep** [MaxToyberman/react-native-ssl-pinning#77]
Whenever I am trying to send parameters in a GET request, I get 500 from the server. The same request with same params and headers works fine in postman.

Do we have to do something differently?
url?param1=param&param2=param

Right now just checked on Android.

RN: 0.60.0
react-native-ssl-pinning: 1.4.6

**Comment by MaxToyberman** [comment]
@annkiitagrawaal-gep  please install react-native-ssl-pinning from this link:
git+https://github.com/MaxToyberman/react-native-ssl-pinning#ISSUE-77

and add params object to the request: 

```
    fetch('https://api.edchild.com', {
      method: 'GET',
      params: {
        param1: "param",
        param2: "param"
      },
      headers: headers,
    })
```

If this works I will release new version

**Comment by MaxToyberman** [comment]
@annkiitagrawaal-gep  did you check ?
