### ISSUE TITLE
Cookie issue

### ISSUE THREAD

**Issue by subhechhu** [MaxToyberman/react-native-ssl-pinning#78]
There has been a cookie issue with my application. Cookie isn't being stored persistently. Is it something to be handled manually or do we have any setting like "Credentials" as in react-native fetch?
The application works fine for the first time but when I kill the app and try to access it, it fails.
Would be great if you could suggest something on this.

**Comment by MaxToyberman** [comment]
@subhechhu  cookies should be persisted.
This library uses `https://github.com/franmontiel/PersistentCookieJar` to persist cookies.
You don't have cookies at all ?

**Comment by akhileshagrhari** [comment]
@MaxToyberman , I'm facing the same issue in my app. Does "react-native-ssl-pinning" not save cookies persistently ?
