### ISSUE TITLE
Please confirm license, hopefully MIT

### ISSUE THREAD

**Issue by rturk** [MaxToyberman/react-native-ssl-pinning#8]
HI @MaxToyberman thanks for build this repo and sharing with the community can you please confirm license grants? Hopefully MIT?

**Comment by MaxToyberman** [comment]
Hi @rturk , I confirm that this library is using MIT license, i will update the readme

**Comment by shridharbavannawar** [comment]
Hi @MaxToyberman , any update on the license?
