### ISSUE TITLE
Requests not executed

### ISSUE THREAD

**Issue by fesoares** [MaxToyberman/react-native-ssl-pinning#82]
Hello,

I'm trying to make a POST for my API but debugging the library's index the console doesn't run:

RNSslPinning.fetch(url, obj, (err, res) => {
        console.log('called');
});

I'm currently running with disableAllSecurity as true, but the .cer has been put in the right place

does anyone know what may be happening?

React Native: 0.61.5
Platform: iOS Simulator

**Comment by MaxToyberman** [comment]
@fesoares what do you have in err ? try to use it like this : 

```
RNSslPinning.fetch(url, obj)
.then(res => console.log('called')
.catch(e => console.log(e))
```

**Comment by fesoares** [comment]
this function is the one inside react-native-ssl-pinning in node_modules, should I change it to a promise?

this function is in ../node_modules/react-native-ssl-pinning/index.js

I tried to switch to promise but it was not possible because RNSslPinning.fetch () needs the 3 parameters

**Comment by MaxToyberman** [comment]
@fesoares you need to switch it to promise.
