### ISSUE TITLE
Error handling for string type 

### ISSUE THREAD

**Issue by VenkateshDoodleBlue** [MaxToyberman/react-native-ssl-pinning#83]
Hi,

Can you help me out, How to handle the string error type. Because when error response come under the json system understand and everything is fine but some cases error response getting as a string, In that system does not know to react. For your reference I will share the screenshot below. 
![Screenshot 2020-07-09 at 10 18 02 AM](https://user-images.githubusercontent.com/30199635/86998207-827e6780-c1cd-11ea-884e-ef9da07041d2.png)

**Comment by MaxToyberman** [comment]
Hi @VenkateshDoodleBlue  
can you check with latest version 1.5.4 ?
