### ISSUE TITLE
Do you need to eject / expo eject when using this on an expo project?

### ISSUE THREAD

**Issue by exposedloser** [MaxToyberman/react-native-ssl-pinning#88]
Not sure if the setup is anything different for an expo project.

**Comment by MaxToyberman** [comment]
Hi @exposedloser never worked with expo before but I created an empty expo project, and it works without ejecting.

**Comment by mrmarktyy** [comment]
Hopefully we can have a guide in terms of how to install the library with Expo managed flow (without eject) with EAS Build config or hooks ?
