### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by davidbiller** [MaxToyberman/react-native-ssl-pinning#9]
i get this after install:

Could not find com.github.franmontiel:PersistentCookieJar:v1.0.1.
Searched in the following locations:
    file:/Users/davidbiller/Library/Android/sdk/extras/m2repository/com/github/franmontiel/PersistentCookieJar/v1.0.1/PersistentCookieJar-v1.0.1.pom

....

Required by:
    project :app > project :react-native-ssl-pinning

**Comment by davidbiller** [comment]
`file:/Users/davidbiller/Library/Android/sdk/extras/m2repository/com/github/franmontiel/PersistentCookieJar/v1.0.1/PersistentCookieJar-v1.0.1.pom
    file:/Users/davidbiller/Library/Android/sdk/extras/m2repository/com/github/franmontiel/PersistentCookieJar/v1.0.1/PersistentCookieJar-v1.0.1.jar
    file:/Users/davidbiller/Library/Android/sdk/extras/google/m2repository/com/github/franmontiel/PersistentCookieJar/v1.0.1/PersistentCookieJar-v1.0.1.pom
    file:/Users/davidbiller/Library/Android/sdk/extras/google/m2repository/com/github/franmontiel/PersistentCookieJar/v1.0.1/PersistentCookieJar-v1.0.1.jar
    file:/Users/davidbiller/Library/Android/sdk/extras/android/m2repository/com/github/franmontiel/PersistentCookieJar/v1.0.1/PersistentCookieJar-v1.0.1.pom
    file:/Users/davidbiller/Library/Android/sdk/extras/android/m2repository/com/github/franmontiel/PersistentCookieJar/v1.0.1/PersistentCookieJar-v1.0.1.jar
    file:/Users/davidbiller/.m2/repository/com/github/franmontiel/PersistentCookieJar/v1.0.1/PersistentCookieJar-v1.0.1.pom
    file:/Users/davidbiller/.m2/repository/com/github/franmontiel/PersistentCookieJar/v1.0.1/PersistentCookieJar-v1.0.1.jar
    https://dl.google.com/dl/android/maven2/com/github/franmontiel/PersistentCookieJar/v1.0.1/PersistentCookieJar-v1.0.1.pom
    https://dl.google.com/dl/android/maven2/com/github/franmontiel/PersistentCookieJar/v1.0.1/PersistentCookieJar-v1.0.1.jar
    https://jcenter.bintray.com/com/github/franmontiel/PersistentCookieJar/v1.0.1/PersistentCookieJar-v1.0.1.pom
    https://jcenter.bintray.com/com/github/franmontiel/PersistentCookieJar/v1.0.1/PersistentCookieJar-v1.0.1.jar
    file:/Users/davidbiller/Desktop/Developer/wehb/node_modules/react-native/android/com/github/franmontiel/PersistentCookieJar/v1.0.1/PersistentCookieJar-v1.0.1.pom
    file:/Users/davidbiller/Desktop/Developer/wehb/node_modules/react-native/android/com/github/franmontiel/PersistentCookieJar/v1.0.1/PersistentCookieJar-v1.0.1.jar
Required by:`

**Comment by envyTang** [comment]
@davidbiller Same problem, is there a solution？

**Comment by alextuagt** [comment]
@davidbiller 
Try add this to your  build.gradle:

allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}

**Comment by MaxToyberman** [comment]
@envyTang @davidbiller  did you solve the problem?

**Comment by filiptdz** [comment]
I think it is important to add that you shouldn't add two urls to the same maven entry, since only one of them will be picked up. The correct modification is:
```
allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven { url "https://jitpack.io" }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

I don't know if this only happens on the latest version of React Native, but it might be beneficial to either add to the documentation or the linking process.
