### ISSUE TITLE
Getting "Unable to resolve host <hostname>: No address associated with hostname" when making fetch request

### ISSUE THREAD

**Issue by PhillJaySaw** [MaxToyberman/react-native-ssl-pinning#91]
Hi, I'm using your library in my React Native project in Redux actions. I have 3 .cer files that I need to use for connecting to the host, but right now, whenever I make a request I get the response "Unable to resolve host...". I have to use a VPN to connect to the host, so this error sounds like im not connected to the VPN, but I'm 100% sure that I am. This only started happening when I began using your library. Before that, I had to enable debugging and use the option "enable network inspect" to somehow bypass SSL and get my request to the server. That's why I need to pin the certificates now by my self, so I can make requests in the final app on a phone.

I might also add that i got 3 .crt files from the host admin, which I then converted to .cer using openssl. 

I'm not sure if my problem is caused by your library but maybe you have some ideas. Thanks in advance!

and here is my request code, which is working when im not using cert pinning
```javascript
return (dispatch) => {
    dispatch({type: USER_LOGIN_PENDING});
    return fetch(`${API_URL}/${URLS.LOGIN}`, {
      method: 'POST',
      timeoutInterval: 10000,
      headers: defaultHeaders(),
      sslPinning: {
        certs: ['cert-root', 'cer-01', 'cer-01'],
      },
      body: JSON.stringify({
        login,
        password,
        phoneNumber,
        deviceId,
        appVersion,
        systemVersion,
      }),
    })
      .then(async (response) => {
        if (response.status === 200 || response.status === 204) {
          return response.json();
        }
        const newError = new Error();
        const errorResponse = await response.json();
        throw Object.assign(newError, errorResponse);
      })
      .then((responseData) =>
        dispatch({
          type: USER_LOGIN_SUCCESS,
          payload: {data: responseData},
        }),
      )
      .catch((error) =>
        dispatch({
          type: USER_LOGIN_FAILURE,
          payload: {error},
        }),
      );
  };
```

**Comment by MaxToyberman** [comment]
@PhillJaySaw this happens both on android and iOS ?

**Comment by PhillJaySaw** [comment]
The app I'm working on is only being developed for android, so I didn't have a chance to test this on iOS. After some more digging, I believe this is not a problem with the library, but the VPN configuration I'm connected to. I tested the app on other computers, and the same issue occurred on windows and mac computers, but not on Linux. So I'm not sure this is a problem with your library.

**Comment by MaxToyberman** [comment]
@PhillJaySaw doesn't sound like a library issue, i am closing feel free to reopen if this is a library issue
