### ISSUE TITLE
Cannot upload to Apple Store because of usage of UIWebKit instead of WKWebView by AFNetworking 3.1.2

### ISSUE THREAD

**Issue by dpailma** [MaxToyberman/react-native-ssl-pinning#98]
I cannot upload the app that uses react-native-ssl-pinning to Apple Store Testflight (using fastlane) and the following issue was emailed by App Store Connect:

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

Upon checking, the following seems to be the issue:
* react-native-ssl-pinning 1.5.0 (@latest) uses AFNetworking 3.1.2
* AFNetworking 3.0 uses UIWebKit and AFNetworking 4.0 uses WKWebView
* Source code with UIWebKit was no longer allowed to be uploaded to App Store starting April 2020. Source code should now use WKWebView.

Is there a workaround or a fix for this? (I am a little confused if I am the only one experiencing this since April 2020, maybe I just missed something)

Thank you.

**Comment by martabacc** [comment]
Are you tryinig to publish new app or updating existing app?

**Comment by dpailma** [comment]
I am trying to publish a new app.

**Comment by martabacc** [comment]
Yeah, the deadline for UIWebView removal for new app submission is April 2020...
You can try writing it natively perhaps?

Been scouring this repo for a week and didn't find any mentions regarding this issue so ... hmm

**Comment by dpailma** [comment]
Ah, I see.
Writing it natively was my last resort.
May I know if there is no plan to update react-native-ssl-pinning to use AFNetworking 4.0?

**Comment by MaxToyberman** [comment]
@dpailma Thank you for reporting this ! 
i will try to upgrade it during the weekend,  a pr is also welcomed.

Have a great day

**Comment by dpailma** [comment]
> a pr is also welcomed.

Ah, sorry, no PR yet.

**Comment by MaxToyberman** [comment]
@dpailma  @martabacc 
https://github.com/MaxToyberman/react-native-ssl-pinning/pull/99

version 1.5.1 now contains AFNetworking 4.0
